import streamlit as st
import sys
import os
import re
import html
import datetime

sys.path.insert(0, os.path.dirname(os.path.dirname(__file__)))
from utils import render_page_header, render_app_sidebar, GLOBAL_UI_CSS

try:
    st.set_page_config(
        page_title="Datasheet Pompa — PLTU TBK",
        page_icon="📋",
        layout="wide",
        initial_sidebar_state="expanded",
    )
except Exception:
    pass

st.markdown(
    "<style>[data-testid='stSidebarNav'] { display: none !important; } section[data-testid='stSidebar'] > div:first-child { padding-top: 1rem; }</style>",
    unsafe_allow_html=True,
)
st.markdown(GLOBAL_UI_CSS, unsafe_allow_html=True)

render_app_sidebar()
render_page_header("📋 Datasheet Pompa & Peralatan Utama PLTU TBK")
st.caption("Spesifikasi teknis peralatan langsung dari file datasheet PLTU Tanjung Balai Karimun — pilih peralatan dari dropdown.")

# ── Render HTML ─────────────────────────────────────────────────────────────
TABLE_CSS = """
<style>
.ds-wrap{overflow-x:auto;margin:.25rem 0 1.4rem 0;border:1px solid rgba(128,128,128,.3);border-radius:10px;}
table.ds{border-collapse:separate;border-spacing:0;table-layout:fixed;width:100%;min-width:760px;font-size:.9rem;line-height:1.4;}
table.ds td{padding:7px 10px;vertical-align:middle;overflow-wrap:anywhere;}
table.ds td.c{border-right:1px solid rgba(128,128,128,.18);border-bottom:1px solid rgba(128,128,128,.18);}
table.ds td.sec{background:#1f5f8b;color:#fff;font-weight:700;text-align:center;letter-spacing:.05em;border-color:rgba(255,255,255,.22);}
table.ds td.lbl{background:rgba(128,128,128,.12);font-weight:600;}
table.ds td.no{background:rgba(31,95,139,.16);color:#2f86c0;font-weight:700;text-align:center;font-variant-numeric:tabular-nums;}
table.ds tr:hover td.c:not(.sec){background:rgba(31,95,139,.10);}
table.ds td.nw{white-space:nowrap;overflow-wrap:normal;padding-left:4px;padding-right:4px;}
table.ds mark{background:#ffd54f;color:#000;padding:0 3px;border-radius:3px;}
.ds-info{display:flex;flex-wrap:wrap;gap:.5rem;margin:.25rem 0 .9rem 0;}
.ds-chip{background:rgba(31,95,139,.12);border:1px solid rgba(31,95,139,.35);border-radius:999px;padding:3px 14px;font-size:.82rem;}
</style>
"""
st.markdown(TABLE_CSS, unsafe_allow_html=True)


def _cell_html(text, kw_re):
    if kw_re is None:
        return html.escape(text).replace("$", "&#36;")
    parts = kw_re.split(text)
    out = []
    for i, p in enumerate(parts):
        e = html.escape(p).replace("$", "&#36;")
        out.append(f"<mark>{e}</mark>" if i % 2 == 1 else e)
    return "".join(out)


def _style_class(text, cls, cs):
    flags = cls.split()
    bold, fill = "b" in flags, "f" in flags
    if re.fullmatch(r"\d{1,2}\.", text):
        return "no"
    if bold and text.lower() in ("no.", "no"):
        return "sec"
    if bold and (cs >= 3 or text.isupper()):
        return "sec"
    if bold or fill:
        return "lbl"
    return ""


def table_html(rows, col_pct, kw_re):
    cols = "".join(f'<col style="width:{p}%">' for p in col_pct)
    body = []
    for cells in rows:
        tds = []
        for text, cs, rs, cls, align in cells:
            attrs = ""
            if cs > 1:
                attrs += f' colspan="{cs}"'
            if rs > 1:
                attrs += f' rowspan="{rs}"'
            if text is None:
                tds.append(f"<td{attrs}></td>")
                continue
            style = f' style="text-align:{align}"' if align in ("center", "right") else ""
            nw = " nw" if cs == 1 and len(text) <= 6 and " " not in text else ""
            tds.append(f'<td class="c {_style_class(text, cls, cs)}{nw}"{attrs}{style}>{_cell_html(text, kw_re)}</td>')
        body.append("<tr>" + "".join(tds) + "</tr>")
    return f'<div class="ds-wrap"><table class="ds"><colgroup>{cols}</colgroup>{"".join(body)}</table></div>'


def count_hits(sheet, kw_re):
    if kw_re is None:
        return 0
    n = 0
    for seg in sheet["segments"]:
        if seg[0] != "table":
            continue
        for cells in seg[1]:
            for text, *_ in cells:
                if text and kw_re.search(text):
                    n += 1
    n += sum(1 for v in [sheet["name"], *sheet["info"].values()] if kw_re.search(v))
    return n


def render_images(files):
    paths = [p for p in (os.path.join(IMG_DIR, f) for f in files) if os.path.exists(p)]
    if not paths:
        return
    st.markdown("**📷 Foto / Gambar**")
    for start in range(0, len(paths), 2):
        cols = st.columns(2)
        for col, p in zip(cols, paths[start:start + 2]):
            with col:
                try:
                    st.image(p, use_container_width=True)
                except TypeError:
                    st.image(p, use_column_width=True)


current_dir = os.path.dirname(os.path.abspath(__file__))
root_dir = os.path.dirname(current_dir)

# Foto peralatan: folder `datasheet_img` di folder utama project (opsional)
IMG_DIR = os.path.join(root_dir, "datasheet_img")
if not os.path.isdir(IMG_DIR):
    IMG_DIR = os.path.join(current_dir, "datasheet_img")


def clean_name(n):
    """'1. CCWP' → 'CCWP' (hilangkan nomor urut di depan nama sheet)."""
    return re.sub(r"^\s*\d+\s*[.)-]\s*", "", n).strip()


def main():
    sheets = DATA
    sheet_names = list(sheets.keys())

    c_select, c_search = st.columns([1.6, 2])

    with c_search:
        keyword = st.text_input(
            "🔍 Cari spesifikasi / part number / merek:",
            placeholder="Contoh: 6305, Head, Torishima, Teco...",
        )
    kw = keyword.strip()
    kw_re = re.compile(f"({re.escape(kw)})", re.IGNORECASE) if kw else None
    hits = {n: count_hits(sheets[n], kw_re) for n in sheet_names}

    # Saat mencari, daftar dropdown otomatis dipersempit ke peralatan yang cocok
    options = [n for n in sheet_names if hits[n]] if kw else sheet_names

    with c_select:
        if not options:
            st.selectbox("📑 Pilih peralatan:", ["— tidak ada hasil —"], disabled=True)
        else:
            selected = st.selectbox(
                "📑 Pilih peralatan:",
                options,
                format_func=lambda n: f"{clean_name(n)}  ({hits[n]} cocok)" if kw else clean_name(n),
            )

    if not options:
        st.info("Tidak ada data yang cocok dengan kata kunci pencarian.")
        return
    if kw:
        st.caption(f"{len(options)} dari {len(sheet_names)} peralatan mengandung “{kw}”.")

    sheet = sheets[selected]
    st.subheader(sheet["name"] or selected)
    if sheet["info"]:
        chips = "".join(
            f'<span class="ds-chip"><b>{html.escape(k.upper())}</b>: {_cell_html(v, kw_re)}</span>'
            for k, v in sheet["info"].items()
        )
        st.markdown(f'<div class="ds-info">{chips}</div>', unsafe_allow_html=True)
    for seg in sheet["segments"]:
        if seg[0] == "table":
            col_pct = seg[2] if len(seg) > 2 else sheet["col_pct"]
            st.markdown(table_html(seg[1], col_pct, kw_re), unsafe_allow_html=True)
        else:
            render_images(seg[1])


# ════════════════════════════════════════════════════════════════════════════
# DATA DATASHEET (tertanam langsung dari file Excel — tidak perlu file Excel/upload)
# Format sel: (teks, colspan, rowspan, kelas, align). teks None = sel kosong pengisi.
# ════════════════════════════════════════════════════════════════════════════
DATA = {'1. CCWP': {'name': 'CLOSE COOLING WATER PUMP ( CCWP )',
             'info': {},
             'col_pct': [4.44, 5.26, 13.96, 6.07, 8.43, 4.53, 6.8, 6.07, 14.33, 2.72, 6.07, 3.62, 17.68],
             'segments': [('table',
                           [[('SPECIFICATION', 13, 1, 'b', 'center')],
                            [('NO.', 1, 1, 'b', ''), ('PUMP', 6, 1, 'b', 'center'), ('NO.', 1, 1, 'b', ''), ('MOTOR', 5, 1, 'b', 'center')],
                            [('1.', 1, 1, '', 'center'), ('MEREK', 2, 1, '', 'left'), ('TORISHIMA PUMP', 4, 1, '', 'center'),
                             ('1.', 1, 1, '', 'center'), ('MEREK', 2, 1, '', 'left'), ('TECO. ELEC. & MACH. PTE. LTD', 3, 1, '', 'center')],
                            [('2.', 1, 1, '', 'center'), ('TYPE & SIZE', 2, 1, '', 'left'), ('CPEN 25 - 200', 4, 1, '', 'center'),
                             ('2.', 1, 1, '', 'center'), ('CODE', 2, 1, '', 'left'), ('AEEBKB 020004 YU', 3, 1, '', 'center')],
                            [('3.', 1, 1, '', 'center'), ('PRODUCT NO.', 2, 1, '', 'left'), ('T. 1080444', 4, 1, '', 'center'),
                             ('3.', 1, 1, '', 'center'), ('2 POLE', 2, 1, '', 'left'), ('50', 1, 1, '', 'center'), ('HZ', 2, 1, '', 'center')],
                            [('4.', 1, 1, '', 'center'), ('TOTAL HEAD', 2, 1, '', 'left'), ('43.8', 1, 1, '', 'center'), ('M', 3, 1, '', 'center'),
                             ('4.', 1, 2, '', 'center'), ('OUTPUT', 2, 2, '', 'left'), ('4', 1, 1, '', 'center'), ('HP', 2, 1, '', 'center')],
                            [('5.', 1, 1, '', 'center'), ('CAPACITY', 2, 1, '', 'left'), ('6', 1, 1, '', 'center'), ('M3/H', 1, 1, '', 'center'),
                             ('2 X 100%', 2, 1, '', 'center'), ('3', 1, 1, '', 'center'), ('KW', 2, 1, '', 'center')],
                            [('6.', 1, 1, '', 'center'), ('SPEED', 2, 1, '', 'left'), ('2900', 1, 1, '', 'center'), ('RPM', 3, 1, '', 'center'),
                             ('5.', 1, 1, '', 'center'), ('VOLT', 2, 1, '', 'left'), ('380', 1, 1, '', 'center'), ('VOLT', 2, 1, '', 'center')],
                            [('7.', 1, 1, '', 'center'), ('DRIVER', 2, 1, '', 'left'), ('3', 1, 1, '', 'center'), ('KW', 3, 1, '', 'center'),
                             ('6.', 1, 1, '', 'center'), ('CURRENT', 2, 1, '', 'left'), ('6.06', 1, 1, '', 'center'),
                             ('AMPERE', 2, 1, '', 'center')],
                            [('8.', 1, 2, '', 'center'), ('BEARING NO.', 2, 2, '', 'left'), ('FRONT', 1, 1, '', 'center'),
                             ('6305 DDU C3', 2, 1, '', 'center'), ('1 PCS', 1, 1, '', 'center'), ('7.', 1, 2, '', 'center'),
                             ('BEARING NO.', 2, 2, '', 'left'), ('FRONT', 1, 1, '', 'center'), ('6206 ZZ', 2, 1, '', 'center')],
                            [('REAR', 1, 1, '', 'center'), ('6305 DDU C3', 2, 1, '', 'center'), ('1 PCS', 1, 1, '', 'center'),
                             ('REAR', 1, 1, '', 'center'), ('6305 ZZ', 2, 1, '', 'center')],
                            [('9.', 1, 1, '', 'center'), ('DELIVERY TIME', 2, 1, '', 'left'), ('OCT 2010', 4, 1, '', 'center'),
                             ('8.', 1, 1, '', 'center'), ('SPEED', 2, 1, '', 'left'), ('2854', 1, 1, '', 'center'), ('RPM', 2, 1, '', 'center')],
                            [('PUMP DESIGN', 7, 2, 'b', 'center'), ('9.', 1, 1, '', 'center'), ('SER. NO', 2, 1, '', 'left'),
                             ('1579000394 . 35', 3, 1, '', 'center')],
                            [('10.', 1, 2, '', 'center'), ('FAN BLADE', 2, 2, '', 'left'), ('TYPE', 1, 1, '', 'center'),
                             ('100 L', 2, 1, '', 'center')],
                            [('KKS NO.', 3, 1, '', 'left'), ('AP - 1105 C/D', 4, 1, '', 'center'), ('NO.', 1, 1, '', 'center'),
                             ('314000039', 2, 1, '', 'center')],
                            [('NO.', 3, 1, '', 'left'), ('2 UNIT ( 2 X 100% )', 4, 1, '', 'center'), ('11.', 1, 1, '', 'center'),
                             ('AMB. TEMP', 2, 1, '', 'left'), ('40', 1, 1, '', 'center'), ('°C', 2, 1, '', 'center')],
                            [('SUCTION PRESSURE', 3, 1, '', 'left'), ('0.45', 1, 1, '', 'center'), ('KG/CM2 G', 3, 1, '', 'center'),
                             ('12.', 1, 1, '', 'center'), ('FRAME SIZE', 2, 1, '', 'left'), ('100 L', 3, 1, '', 'center')],
                            [('DISCHARGE PRESSURE', 3, 1, '', 'left'), ('4.84', 1, 1, '', 'center'), ('KG/CM2 G', 3, 1, '', 'center'),
                             ('SYSTEM', 2, 1, 'b', 'center'), ('CLOSE COOLING WATER SYSTEM', 4, 1, '', 'center')],
                            [('DIFFERENTIAL PRESS.', 3, 1, '', 'left'), ('4.38', 1, 1, '', 'center'), ('KG/CM2 G', 3, 1, '', 'center'),
                             ('DRAWING NO.', 2, 1, 'b', 'center'), ('1802-00-M-10-PG-001-02', 4, 1, '', 'center')]],
                           [4.44, 5.26, 13.96, 6.07, 8.43, 4.53, 6.8, 6.07, 14.33, 2.72, 6.07, 3.62, 17.68]),
                          ('images', ['s01_1.jpg', 's01_2.jpg']),
                          ('table',
                           [[('BEARING SPECIFICATION', 5, 1, 'b', 'center'), ('TYPE : 6305 DDU KOYO DEEP GROOVE BEARING', 8, 1, 'b', 'center')],
                            [('1.', 1, 1, '', 'center'), ('BRAND', 3, 1, '', ''), ('KOYO', 9, 1, '', '')],
                            [('2.', 1, 1, '', 'center'), ('TYPE', 3, 1, '', ''), ('6305 DDU C3', 9, 1, '', '')],
                            [('3.', 1, 1, '', 'center'), ('INSIDE DIAMETER', 3, 1, '', ''), ('25 MM', 9, 1, '', '')],
                            [('4.', 1, 1, '', 'center'), ('OUTSIDE DIAMETER', 3, 1, '', ''), ('62 MM', 9, 1, '', '')],
                            [('5.', 1, 1, '', 'center'), ('WIDTH', 3, 1, '', ''), ('17 MM', 9, 1, '', '')],
                            [('6.', 1, 1, '', 'center'), ('CLEARANCE', 3, 1, '', ''), ('C3', 9, 1, '', '')],
                            [('7.', 1, 1, '', 'center'), ('MODEL', 3, 1, '', ''), ('TWO RUBBER SEALS ( 2RS )', 9, 1, '', '')],
                            [('8.', 1, 1, '', 'center'), ('PRICE ( 2013 )', 3, 1, '', ''), ('£ 8.30', 9, 1, '', '')]],
                           [4.44, 5.26, 13.96, 6.07, 8.43, 4.53, 6.8, 6.07, 14.33, 2.72, 6.07, 3.62, 17.68])]},
 '2. BOOSTER PUMP': {'name': 'COOLING BOOSTER PUMP',
                     'info': {},
                     'col_pct': [4.02, 6.45, 13.47, 6.27, 8.7, 4.68, 7.76, 4.02, 13.57, 2.81, 6.27, 3.74, 18.25],
                     'segments': [('table',
                                   [[('SPECIFICATION', 13, 1, 'b', 'center')],
                                    [('NO.', 1, 1, 'b', ''), ('PUMP', 6, 1, 'b', 'center'), ('NO.', 1, 1, 'b', ''), ('MOTOR', 5, 1, 'b', 'center')],
                                    [('1.', 1, 1, '', 'center'), ('MEREK', 2, 1, '', 'left'), ('TORISHIMA PUMP', 4, 1, '', 'center'),
                                     ('1.', 1, 1, '', 'center'), ('MEREK', 2, 1, '', 'left'), ('TECO. ELEC. & MACH. PTE. LTD', 3, 1, '', 'center')],
                                    [('2.', 1, 1, '', 'center'), ('TYPE & SIZE', 2, 1, '', 'left'), ('ETA - N 125 X 100 - 315', 4, 1, '', 'center'),
                                     ('2.', 1, 1, '', 'center'), ('CODE', 2, 1, '', 'left'), ('AEEBKB.040030 FBB', 3, 1, '', 'center')],
                                    [('3.', 1, 1, '', 'center'), ('PRODUCT NO.', 2, 1, '', 'left'), ('TS. 1018269', 4, 1, '', 'center'),
                                     ('3.', 1, 1, '', 'center'), ('4 POLE', 2, 1, '', 'left'), ('50', 1, 1, '', 'center'),
                                     ('HZ', 2, 1, '', 'center')],
                                    [('4.', 1, 1, '', 'center'), ('TOTAL HEAD', 2, 1, '', 'left'), ('33.9', 1, 1, '', 'center'),
                                     ('M', 3, 1, '', 'center'), ('4.', 1, 2, '', 'center'), ('OUTPUT', 2, 2, '', 'left'), ('30', 1, 1, '', 'center'),
                                     ('HP', 2, 1, '', 'center')],
                                    [('5.', 1, 1, '', 'center'), ('CAPACITY', 2, 1, '', 'left'), ('154', 1, 1, '', 'center'),
                                     ('M3/H', 1, 1, '', 'center'), ('2 X 100%', 2, 1, '', 'center'), ('22', 1, 1, '', 'center'),
                                     ('KW', 2, 1, '', 'center')],
                                    [('6.', 1, 1, '', 'center'), ('SPEED', 2, 1, '', 'left'), ('1460', 1, 1, '', 'center'),
                                     ('RPM', 3, 1, '', 'center'), ('5.', 1, 1, '', 'center'), ('VOLT', 2, 1, '', 'left'),
                                     ('380 - 415', 2, 1, '', 'center'), ('VOLT', 1, 1, '', 'center')],
                                    [('7.', 1, 1, '', 'center'), ('DRIVER', 2, 1, '', 'left'), ('22', 1, 1, '', 'center'), ('KW', 3, 1, '', 'center'),
                                     ('6.', 1, 1, '', 'center'), ('CURRENT', 2, 1, '', 'left'), ('40.8', 1, 1, '', 'center'),
                                     ('AMPERE', 2, 1, '', 'center')],
                                    [('8.', 1, 2, '', 'center'), ('BEARING NO.', 2, 1, '', 'left'), ('FRONT', 1, 1, '', 'center'),
                                     ('6309 DDU C3', 2, 1, '', 'center'), ('1 PCS', 1, 1, '', 'center'), ('7.', 1, 2, '', 'center'),
                                     ('BEARING NO.', 2, 2, '', 'left'), ('FRONT', 1, 1, '', 'center'), ('6611 ZZ', 2, 1, '', 'center')],
                                    [(None, 2, 1, '', ''), ('REAR', 1, 1, '', 'center'), ('6309 DDU C3', 2, 1, '', 'center'),
                                     ('1 PCS', 1, 1, '', 'center'), ('REAR', 1, 1, '', 'center'), ('6310 ZZ', 2, 1, '', 'center')],
                                    [('9.', 1, 1, '', 'center'), ('DELIVERY TIME', 2, 1, '', 'left'), ('OCT 2010', 4, 1, '', 'center'),
                                     ('8.', 1, 1, '', 'center'), ('SPEED', 2, 1, '', 'left'), ('1460', 1, 1, '', 'center'),
                                     ('RPM', 2, 1, '', 'center')],
                                    [('PUMP DESIGN', 7, 1, 'b', ''), ('9.', 1, 1, '', 'center'), ('SER. NO', 2, 1, '', 'left'),
                                     ('H6106703. 088', 3, 1, '', 'center')],
                                    [(None, 7, 1, '', ''), ('10.', 1, 2, '', 'center'), ('FAN BLADE', 2, 2, '', 'left'), ('TYPE', 1, 1, '', 'center'),
                                     ('180 L.C', 2, 1, '', 'center')],
                                    [('KKS NO.', 3, 1, '', 'left'), ('AP - 1110 C/D', 4, 1, '', 'center'), ('NO.', 1, 1, '', 'center'),
                                     ('31402 C103', 2, 1, '', 'center')],
                                    [('NO.', 3, 1, '', 'left'), ('2 UNIT ( 2 X 100% )', 4, 1, '', 'center'), ('11.', 1, 1, '', 'center'),
                                     ('AMB. TEMP', 2, 1, '', 'left'), ('40', 1, 1, '', 'center'), ('°C', 2, 1, '', 'center')],
                                    [('SUCTION PRESSURE', 3, 1, '', 'left'), ('1', 1, 1, '', 'center'), ('KG/CM2 G', 3, 1, '', 'center'),
                                     ('12.', 1, 1, '', 'center'), ('FRAME SIZE', 2, 1, '', 'left'), ('180 L.C', 3, 1, '', 'center')],
                                    [('DISCHARGE PRESSURE', 3, 1, '', 'left'), ('3', 1, 1, '', 'center'), ('KG/CM2 G', 3, 1, '', 'center'),
                                     ('SYSTEM', 2, 1, '', 'center'), ('SEA WATER COOLING SUPPLY SYSTEM', 4, 1, '', 'center')],
                                    [('DIFFERENTIAL PRESS.', 3, 1, '', 'left'), ('2', 1, 1, '', 'center'), ('KG/CM2 G', 3, 1, '', 'center'),
                                     ('DRAWING NO.', 2, 1, '', 'center'), ('1802-00-M-10-P-001-01', 4, 1, '', 'center')]],
                                   [4.02, 6.45, 13.47, 6.27, 8.7, 4.68, 7.76, 4.02, 13.57, 2.81, 6.27, 3.74, 18.25]),
                                  ('images', ['s02_1.jpg'])]},
 '3. BFP': {'name': 'BOILER FEED WATER PUMP ( BFP )',
            'info': {},
            'col_pct': [4.89, 7.24, 6.86, 6.3, 8.74, 4.7, 6.48, 4.89, 14.85, 2.82, 6.3, 6.3, 19.65],
            'segments': [('table',
                          [[('SPECIFICATION', 13, 1, 'b', 'center')],
                           [('NO.', 1, 1, 'b', ''), ('PUMP', 6, 1, 'b', 'center'), ('NO.', 1, 1, 'b', ''), ('MOTOR', 5, 1, 'b', 'center')],
                           [('1.', 1, 2, '', 'center'), ('TYPE & SIZE', 2, 2, '', 'center'), ('MULTI STAGE PUMP', 4, 1, '', 'center'),
                            ('1.', 1, 1, '', 'center'), ('FRAME', 1, 1, '', 'center'), ('Y3-315 L1 - B3', 4, 1, '', 'center')],
                           [('DGJ 45 - 80 X 7', 4, 1, '', 'center'), ('2.', 1, 1, '', 'center'), ('MEREK', 1, 1, '', 'center'),
                            ('3-PHASE INDUCTION MOTOR', 4, 1, '', 'center')],
                           [('2.', 1, 1, '', 'center'), ('HEAD', 2, 1, '', 'center'), ('560', 2, 1, '', 'center'), ('M', 2, 1, '', 'center'),
                            ('3.', 1, 2, '', 'center'), ('OUTPUT', 1, 2, '', 'center'), ('160', 3, 1, '', 'center'), ('KW', 1, 1, '', 'center')],
                           [('3.', 1, 1, '', 'center'), ('DRIVER', 2, 1, '', 'center'), ('125', 2, 1, '', 'center'), ('KW', 2, 1, '', 'center'),
                            ('214.5', 3, 1, '', 'center'), ('HP', 1, 1, '', 'center')],
                           [('4.', 1, 2, '', 'center'), ('CAPACITY', 2, 2, '', 'center'), ('3 X 100 %', 4, 1, '', 'center'),
                            ('4.', 1, 1, '', 'center'), ('EFF', 1, 1, '', 'center'), ('94', 3, 1, '', 'center'), ('%', 1, 1, '', 'center')],
                           [('45', 2, 1, '', 'center'), ('M3/H', 2, 1, '', 'center'), ('5.', 1, 1, '', 'center'),
                            ('POWER FACTOR', 1, 1, '', 'center'), ('0.91', 3, 1, '', 'center'), (None, 1, 1, '', '')],
                           [('5.', 1, 1, '', 'center'), ('SPEED', 2, 1, '', 'center'), ('2986', 2, 1, '', 'center'), ('RPM', 2, 1, '', 'center'),
                            ('6.', 1, 1, '', 'center'), ('FREQUENCY', 1, 1, '', 'center'), ('50', 3, 1, '', 'center'), ('HZ', 1, 1, '', 'center')],
                           [('6.', 1, 1, '', 'center'), ('WEIGHT', 2, 1, '', 'center'), ('1250', 2, 1, '', 'center'), ('KG', 2, 1, '', 'center'),
                            ('7.', 1, 1, '', 'center'), ('VOLT', 1, 1, '', 'center'), ('380', 3, 1, '', 'center'), ('VOLT', 1, 1, '', 'center')],
                           [('7.', 1, 2, '', 'center'), ('PRODUCT', 2, 2, '', 'center'), ('SHENYANG PUMP MANUFACTORY', 4, 2, '', 'center'),
                            ('8.', 1, 1, '', 'center'), ('CURRENT', 1, 1, '', 'center'), ('282.1', 3, 1, '', 'center'),
                            ('AMPERE', 1, 1, '', 'center')],
                           [('9.', 1, 2, '', 'center'), ('BEARING', 1, 1, '', 'center'), ('FRONT', 3, 1, '', 'center'),
                            ('N 6319 C3', 1, 1, '', 'center')],
                           [('DRAWING NO.', 7, 2, 'b', 'center'), (None, 1, 1, '', ''), ('REAR', 3, 1, '', 'center'),
                            ('N 6319 C3', 1, 1, '', 'center')],
                           [('10.', 1, 1, '', 'center'), ('SERIAL NO.', 1, 1, '', 'center'), ('85442', 4, 1, '', 'center')],
                           [('1802 - 00 - M - 09 - LB - 002 - 01', 7, 1, '', 'center'), ('11.', 1, 2, '', 'center'), ('PRODUCT', 1, 2, '', 'center'),
                            ('SHANDONG HUALI ELECTRIC MOTOR GROUP.CO.LTD', 4, 2, '', 'center')],
                           [('1802 - 00 - M - 09 - LB - 003 - 01', 7, 1, '', 'center')], [('WATER HEAT FLOW VALUE', 13, 1, 'b', 'center')],
                           [('NO.', 1, 1, 'b', 'center'), ('SUCTION', 2, 1, 'b', 'center'), ('VALUE', 2, 1, 'b', 'center'),
                            ('UNIT', 2, 1, 'b', 'center'), ('NO.', 1, 1, 'b', 'center'), ('DISCHARGE', 2, 1, 'b', 'center'),
                            ('VALUE', 2, 1, 'b', 'center'), ('UNIT', 1, 1, 'b', 'center')],
                           [('1.', 1, 1, '', 'center'), ('PRESSURE', 2, 1, '', 'left'), ('1.5', 2, 1, '', 'center'), ('BAR. ABS', 2, 1, '', 'center'),
                            ('1.', 1, 1, '', 'center'), ('PRESSURE', 2, 1, '', 'left'), ('55', 2, 1, '', 'center'),
                            ('BAR. ABS', 1, 1, '', 'center')],
                           [('2.', 1, 1, '', 'center'), ('MASS FLOW', 2, 1, '', 'left'), ('35036', 2, 1, '', 'center'),
                            ('KG/HOUR', 2, 1, '', 'center'), ('2.', 1, 1, '', 'center'), ('MASS FLOW', 2, 1, '', 'left'),
                            ('35036', 2, 1, '', 'center'), ('KG/HOUR', 1, 1, '', 'center')],
                           [('3.', 1, 1, '', 'center'), ('WATER TEMP.', 2, 1, '', 'left'), ('104', 2, 1, '', 'center'), ('°C', 2, 1, '', 'center'),
                            ('3.', 1, 1, '', 'center'), ('WATER TEMP.', 2, 1, '', 'left'), ('104', 2, 1, '', 'center'), ('°C', 1, 1, '', 'center')],
                           [('4.', 1, 1, '', 'center'), ('ENTHALPY', 2, 1, '', 'left'), ('109.29', 2, 1, '', 'center'),
                            ('KCAL/KG', 2, 1, '', 'center'), ('4.', 1, 1, '', 'center'), ('ENTHALPY', 2, 1, '', 'left'),
                            ('105.24', 2, 1, '', 'center'), ('KCAL/KG', 1, 1, '', 'center')],
                           [('5.', 1, 1, '', 'center'), ('HEAT FLOW', 2, 1, '', 'left'), ('3.65E+06', 2, 1, '', 'center'),
                            ('KCAL/HOUR', 2, 1, '', 'center'), ('5.', 1, 1, '', 'center'), ('HEAT FLOW', 2, 1, '', 'left'),
                            ('3.69E+06', 2, 1, '', 'center'), ('KCAL/HOUR', 1, 1, '', 'center')]],
                          [4.89, 7.24, 6.86, 6.3, 8.74, 4.7, 6.48, 4.89, 14.85, 2.82, 6.3, 6.3, 19.65]),
                         ('images', ['s03_1.jpg'])]},
 '4. JET PUMP': {'name': 'WATER JET PUMP',
                 'info': {},
                 'col_pct': [4.1, 11.45, 3.53, 6.39, 8.87, 4.77, 10.02, 4.1, 15.08, 2.86, 6.39, 3.81, 18.61],
                 'segments': [('table',
                               [[('SPECIFICATION', 13, 1, 'b', 'center')],
                                [('NO.', 1, 1, 'b', ''), ('PUMP', 6, 1, 'b', 'center'), ('NO.', 1, 1, 'b', ''), ('MOTOR', 5, 1, 'b', 'center')],
                                [('1.', 1, 1, '', 'center'), ('MODEL', 2, 1, '', 'center'), ('IS100 - 65 - 200', 4, 1, '', 'center'),
                                 ('1.', 1, 1, '', 'center'), ('FRAME', 1, 1, '', 'center'), ('Y2 - 180M - 2', 4, 1, '', 'center')],
                                [('2.', 1, 1, '', 'center'), ('ORDER NO.', 2, 1, '', 'center'), ('2008 - M6 - 356', 4, 1, '', 'center'),
                                 ('2.', 1, 2, '', 'center'), ('OUTPUT', 1, 2, '', 'center'), ('22', 2, 1, '', 'center'), ('KW', 2, 1, '', 'left')],
                                [('3.', 1, 1, '', 'center'), ('DRIVER', 2, 1, '', 'center'), ('19.7', 2, 1, '', 'center'), ('KW', 2, 1, '', 'center'),
                                 ('29.5', 2, 1, '', 'center'), ('HP', 2, 1, '', 'left')],
                                [('4.', 1, 2, '', 'center'), ('CAPACITY', 2, 2, '', 'center'), ('2 X 100 %', 4, 1, '', 'center'),
                                 ('3.', 1, 1, '', 'center'), ('VOLT', 1, 1, '', 'center'), ('380', 2, 1, '', 'center'), ('VOLT', 2, 1, '', 'left')],
                                [('120', 2, 1, '', 'center'), ('M3/H', 2, 1, '', 'center'), ('4.', 1, 1, '', 'center'),
                                 ('CURRENT', 1, 1, '', 'center'), ('41.0', 2, 1, '', 'center'), ('AMPERE', 2, 1, '', 'left')],
                                [('5.', 1, 1, '', 'center'), ('SPEED', 2, 1, '', 'center'), ('2900', 2, 1, '', 'center'), ('RPM', 2, 1, '', 'center'),
                                 ('5.', 1, 1, '', 'center'), ('PF', 1, 1, '', 'center'), ('0.9', 4, 1, '', 'center')],
                                [('6.', 1, 1, '', 'center'), ('HEAD', 2, 1, '', 'center'), ('47', 2, 1, '', 'center'), ('M', 2, 1, '', 'center'),
                                 ('6.', 1, 1, '', 'center'), ('FREQUENCY', 1, 1, '', 'center'), ('50', 2, 1, '', 'center'),
                                 ('HZ', 2, 1, '', 'left')],
                                [('7.', 1, 1, '', 'center'), ('SERIES NO.', 2, 1, '', 'center'), ('90214/5', 4, 1, '', 'center'),
                                 ('7.', 1, 1, '', 'center'), ('SPEED', 1, 1, '', 'center'), ('2940', 2, 1, '', 'center'), ('RPM', 2, 1, '', 'left')],
                                [('8.', 1, 1, '', 'center'), ('WEIGHT', 2, 1, '', 'center'), ('320', 2, 1, '', 'center'), ('KG', 2, 1, '', 'center'),
                                 ('8.', 1, 1, '', 'center'), ('WEIGHT', 1, 1, '', 'center'), ('170', 2, 1, '', 'center'), ('KG', 2, 1, '', 'left')],
                                [('9.', 1, 1, '', 'center'), ('EFF', 2, 1, '', 'center'), ('77', 2, 1, '', 'center'), ('%', 2, 1, '', 'center'),
                                 ('9.', 1, 2, '', 'center'), ('PRODUCT', 1, 2, '', 'center'),
                                 ('SHANDONG HUALI ELECTRIC MOTOR GROUP.CO.LTD', 4, 2, '', 'center')],
                                [('10.', 1, 2, '', 'center'), ('CUSTOMER', 2, 2, '', 'center'),
                                 ('SHANDONG MACHINERY I&E GROUP CORPORATION', 4, 2, '', 'center')],
                                [('PUMP DESIGN', 6, 2, 'b', 'center')],
                                [('11.', 1, 2, '', 'center'), ('MANUFACTURER', 2, 2, '', 'center'),
                                 ('SHENYANG PUMP MANUFACTORY', 4, 2, '', 'center')],
                                [('KKS NO.', 2, 1, '', 'left'), ('AP / 1114 A/B', 4, 1, '', 'left')],
                                [('DRAWING NO.', 7, 2, 'b', 'center'), ('FLUID', 2, 1, '', ''), ('CONDENSATE', 4, 1, '', 'left')],
                                [('DES. CAPACITY', 2, 1, '', ''), ('105', 2, 1, '', 'center'), ('M3/H', 2, 1, '', 'left')],
                                [('1802 - 00 - M - 10 - LB - 003 - 02', 7, 2, '', 'center'), ('DISCHARGE PRESS.', 2, 1, '', ''),
                                 ('3.92', 2, 1, '', 'center'), ('KG/CM2 G', 2, 1, '', 'left')],
                                [('EXTRACTION FLOW', 2, 1, '', ''), ('7.5', 2, 1, '', 'center'), ('KG/HR', 2, 1, '', 'left')]],
                               [4.1, 11.45, 3.53, 6.39, 8.87, 4.77, 10.02, 4.1, 15.08, 2.86, 6.39, 3.81, 18.61]),
                              ('images', ['s04_1.jpg'])]},
 '5. AC OIL PUMP': {'name': 'AC AUXILIARY OIL PUMP',
                    'info': {},
                    'col_pct': [4.6, 6.46, 13.98, 2.65, 5.93, 8.23, 4.42, 6.1, 4.6, 13.98, 2.65, 5.93, 5.93, 14.51],
                    'segments': [('table',
                                  [[('SPECIFICATION', 14, 1, 'b', 'center')],
                                   [('NO.', 1, 1, 'b', ''), ('PUMP', 7, 1, 'b', 'center'), ('NO.', 1, 1, 'b', ''),
                                    ('MOTOR ( AC )', 5, 1, 'b', 'center')],
                                   [('1.', 1, 2, '', 'center'), ('MODEL', 2, 2, '', 'left'), ('GEAR OIL PUMP', 5, 1, '', 'center'),
                                    ('1.', 1, 1, '', 'center'), ('MEREK', 1, 1, '', 'center'), ('3 - PHASE INDUCTION MOTOR', 4, 1, '', 'center')],
                                   [('CHY 18 - 1', 5, 1, '', 'center'), ('2.', 1, 1, '', 'center'), ('TYPE', 1, 1, '', 'center'),
                                    ('Y2 - 132 M2 - 6T', 4, 1, '', 'center')],
                                   [('2.', 1, 1, '', 'center'), ('TYPE', 2, 1, '', 'left'), ('POSITIVE DISPLACEMENT', 5, 1, '', 'center'),
                                    ('3.', 1, 1, '', 'center'), ('STANDARD NO.', 1, 1, '', 'center'), ('JB/T8680.1 - 1998', 4, 1, '', 'center')],
                                   [('3.', 1, 1, '', 'center'), ('DRIVER', 2, 1, '', 'left'), ('3.8', 3, 1, '', 'center'), ('KW', 2, 1, '', 'center'),
                                    ('4.', 1, 1, '', 'center'), ('OUTPUT', 1, 1, '', 'center'), ('5.5', 3, 1, '', 'center'),
                                    ('KW', 1, 1, '', 'center')],
                                   [('4.', 1, 1, '', 'center'), ('SPEED', 2, 1, '', 'left'), ('960', 3, 1, '', 'center'), ('RPM', 2, 1, '', 'center'),
                                    ('5.', 1, 1, '', 'center'), ('VOLTAGE', 1, 1, '', 'center'), ('400', 3, 1, '', 'center'),
                                    ('VOLT', 1, 1, '', 'center')],
                                   [('5.', 1, 1, '', 'center'), ('EFF', 2, 1, '', 'left'), ('55', 3, 1, '', 'center'), ('%', 2, 1, '', 'center'),
                                    ('6.', 1, 1, '', 'center'), ('SPEED', 1, 1, '', 'center'), ('960', 3, 1, '', 'center'),
                                    ('RPM', 1, 1, '', 'center')],
                                   [('6.', 1, 1, '', 'center'), ('HEAD ( NPSH )', 2, 1, '', 'left'), ('5', 3, 1, '', 'center'),
                                    ('M', 2, 1, '', 'center'), ('7.', 1, 1, '', 'center'), ('FREQUENCY', 1, 1, '', 'center'),
                                    ('50', 3, 1, '', 'center'), ('HZ', 1, 1, '', 'center')],
                                   [('7.', 1, 2, '', 'center'), ('CAPACITY FLOW', 2, 2, '', 'left'), ('350', 3, 1, '', 'center'),
                                    ('L/MIN', 2, 1, '', 'center'), ('8.', 1, 1, '', 'center'), ('CURRENT', 1, 1, '', 'center'),
                                    ('11.6', 3, 1, '', 'center'), ('AMPERE', 1, 1, '', 'center')],
                                   [('20.5', 3, 1, '', 'center'), ('M3/H', 2, 1, '', 'center'), ('9.', 1, 1, '', 'center'),
                                    ('WEIGHT', 1, 1, '', 'center'), ('71', 3, 1, '', 'center'), ('KG', 1, 1, '', 'center')],
                                   [('8.', 1, 2, '', 'center'), ('PRODUCT', 2, 2, '', 'left'),
                                    ('BOTOUSHI YUNHE ESTATE OF PUMP CO, LTD', 5, 2, '', 'center'), ('10.', 1, 1, '', 'center'),
                                    ('SOUND', 1, 1, '', 'center'), ('69', 3, 1, '', 'center'), ('DB', 1, 1, '', 'center')],
                                   [('11.', 1, 1, '', 'center'), ('PRODUCT', 1, 1, '', 'center'),
                                    ('JIANGSU ELECTRIC MOTOR .CO, LTD', 4, 1, '', 'center')],
                                   [('PUMP DESIGN', 8, 1, 'b', 'center'), ('DRAWING NO.', 6, 1, 'b', 'center')],
                                   [('FLUID', 3, 1, '', 'center'), ('OIL', 5, 1, '', 'center'), ('UNIT 1', 2, 1, '', 'center'),
                                    ('1802 - 00 - M - 10 - P - 002 - 01', 4, 1, '', 'center')],
                                   [('DESIGN PRESSURE', 3, 1, '', 'left'), ('0.353', 3, 1, '', 'center'), ('MPA', 2, 1, '', 'center'),
                                    ('UNIT 2', 2, 1, '', 'center'), ('1803 - 00 - M - 10 - P - 002 - 02', 4, 1, '', 'center')],
                                   [('DIAMETER SHAFT', 3, 1, '', 'left'), ('Ø 70', 3, 1, '', 'center'), ('MM', 2, 1, '', 'center'),
                                    ('SYSTEM', 2, 2, '', 'center'), ('OIL COOLING SYSTEM OF STEAM TURBINE', 4, 2, '', 'center')],
                                   [('WEIGHT', 3, 1, '', 'left'), ('198', 3, 1, '', 'center'), ('KG', 2, 1, '', 'center')]],
                                  [4.6, 6.46, 13.98, 2.65, 5.93, 8.23, 4.42, 6.1, 4.6, 13.98, 2.65, 5.93, 5.93, 14.51]),
                                 ('images', ['s05_1.jpg'])]},
 '6. DC OIL PUMP': {'name': 'DC AUXILIARY OIL PUMP',
                    'info': {},
                    'col_pct': [4.97, 6.59, 7.54, 2.87, 6.4, 8.88, 4.77, 6.59, 4.97, 15.09, 2.87, 6.4, 6.4, 15.66],
                    'segments': [('table',
                                  [[('SPECIFICATION', 14, 1, 'b', 'center')],
                                   [('NO.', 1, 1, 'b', ''), ('PUMP', 7, 1, 'b', 'center'), ('NO.', 1, 1, 'b', ''),
                                    ('MOTOR ( DC )', 5, 1, 'b', 'center')],
                                   [('1.', 1, 2, '', 'center'), ('MODEL', 2, 2, '', 'left'), ('GEAR OIL PUMP', 5, 1, '', 'center'),
                                    ('1.', 1, 1, '', 'center'), ('MEREK', 1, 1, '', 'center'), ("XI'AN SIMO MOTORS, INC", 4, 1, '', 'center')],
                                   [('CHY 18 - 1', 5, 1, '', 'center'), ('2.', 1, 1, '', 'center'), ('TYPE', 1, 1, '', 'center'),
                                    ('Z2 - 61 ( DIRECT CURRENT )', 4, 1, '', 'center')],
                                   [('2.', 1, 1, '', 'center'), ('TYPE', 2, 1, '', 'left'), ('POSITIVE DISPLACEMENT', 5, 1, '', 'center'),
                                    ('3.', 1, 1, '', 'center'), ('STANDARD NO.', 1, 1, '', 'center'), ('Q/XD. 514. 017 - 2006', 4, 1, '', 'center')],
                                   [('3.', 1, 1, '', 'center'), ('DRIVER', 2, 1, '', 'left'), ('3.8', 3, 1, '', 'center'), ('KW', 2, 1, '', 'center'),
                                    ('4.', 1, 1, '', 'center'), ('OUTPUT', 1, 1, '', 'center'), ('5.5', 3, 1, '', 'center'),
                                    ('KW', 1, 1, '', 'center')],
                                   [('4.', 1, 1, '', 'center'), ('SPEED', 2, 1, '', 'left'), ('960', 3, 1, '', 'center'), ('RPM', 2, 1, '', 'center'),
                                    ('5.', 1, 1, '', 'center'), ('VOLTAGE', 1, 1, '', 'center'), ('220', 3, 1, '', 'center'),
                                    ('VOLT', 1, 1, '', 'center')],
                                   [('5.', 1, 1, '', 'center'), ('EFF', 2, 1, '', 'left'), ('55', 3, 1, '', 'center'), ('%', 2, 1, '', 'center'),
                                    ('6.', 1, 1, '', 'center'), ('SPEED', 1, 1, '', 'center'), ('1000', 3, 1, '', 'center'),
                                    ('RPM', 1, 1, '', 'center')],
                                   [('6.', 1, 1, '', 'center'), ('HEAD ( NPSH )', 2, 1, '', 'left'), ('5', 3, 1, '', 'center'),
                                    ('M', 2, 1, '', 'center'), ('7.', 1, 1, '', 'center'), ('CURRENT', 1, 1, '', 'center'),
                                    ('30.3', 3, 1, '', 'center'), ('AMPERE', 1, 1, '', 'center')],
                                   [('7.', 1, 2, '', 'center'), ('CAPACITY FLOW', 2, 2, '', 'left'), ('350', 3, 1, '', 'center'),
                                    ('L/MIN', 2, 1, '', 'center'), ('8.', 1, 1, '', 'center'), ('BEARING', 1, 2, '', 'center'),
                                    ('FRONT', 3, 1, '', 'center'), ('6309/CMZ1', 1, 1, '', 'center')],
                                   [('20.5', 3, 1, '', 'center'), ('M3/H', 2, 1, '', 'center'), ('9.', 1, 1, '', 'center'),
                                    ('REAR', 3, 1, '', 'center'), ('6309/CMZ1', 1, 1, '', 'center')],
                                   [('8.', 1, 2, '', 'center'), ('PRODUCT', 2, 2, '', 'left'),
                                    ('BOTOUSHI YUNHE ESTATE OF PUMP CO, LTD', 5, 2, '', 'center'), ('10.', 1, 1, '', 'center'),
                                    ('WEIGHT', 1, 1, '', 'center'), ('180', 3, 1, '', 'center'), ('KG', 1, 1, '', 'center')],
                                   [('11.', 1, 1, '', 'center'), ('PRODUCT', 1, 1, '', 'center'), ("XI'AN SIMO MOTORS, INC", 4, 1, '', 'center')],
                                   [('PUMP DESIGN', 8, 1, 'b', 'center'), ('DRAWING NO.', 6, 1, 'b', 'center')],
                                   [('FLUID', 3, 1, '', 'left'), ('OIL', 5, 1, '', 'center'), ('UNIT 1', 2, 1, '', 'center'),
                                    ('1802 - 00 - M - 10 - P - 002 - 01', 4, 1, '', 'center')],
                                   [('DESIGN PRESSURE', 3, 1, '', 'left'), ('0.353', 3, 1, '', 'center'), ('MPA', 2, 1, '', 'center'),
                                    ('UNIT 2', 2, 1, '', 'center'), ('1803 - 00 - M - 10 - P - 002 - 02', 4, 1, '', 'center')],
                                   [('DIAMETER SHAFT', 3, 1, '', 'left'), ('Ø 70', 3, 1, '', 'center'), ('MM', 2, 1, '', 'center'),
                                    ('SYSTEM', 2, 2, '', 'center'), ('OIL COOLING SYSTEM OF STEAM TURBINE', 4, 2, '', 'center')],
                                   [('WEIGHT', 3, 1, '', 'left'), ('198', 3, 1, '', 'center'), ('KG', 2, 1, '', 'center')]],
                                  [4.97, 6.59, 7.54, 2.87, 6.4, 8.88, 4.77, 6.59, 4.97, 15.09, 2.87, 6.4, 6.4, 15.66]),
                                 ('images', ['s06_1.jpg'])]},
 '7. CWP ( COOLING TOWER )': {'name': 'CIRCULATING WATER PUMP ( CWP )',
                              'info': {},
                              'col_pct': [4.68, 5.67, 10.89, 2.7, 6.03, 8.37, 4.5, 6.21, 4.68, 16.74, 2.7, 6.03, 6.03, 14.76],
                              'segments': [('table',
                                            [[('SPECIFICATION', 14, 1, 'b', 'center')],
                                             [('NO.', 1, 1, 'b', ''), ('PUMP', 7, 1, 'b', 'center'), ('NO.', 1, 1, 'b', ''),
                                              ('MOTOR', 5, 1, 'b', 'center')],
                                             [('1.', 1, 1, '', 'center'), ('MEREK', 2, 1, '', 'left'), ('TORISHIMA PUMP', 5, 1, '', 'center'),
                                              ('1.', 1, 2, '', 'center'), ('MEREK', 1, 2, '', 'center'),
                                              ('TECO , 3 PHASE INDUCTION MOTOR', 4, 2, '', 'center')],
                                             [('2.', 1, 1, '', 'center'), ('TYPE & SIZE', 2, 1, '', 'left'), ('CDM 450 LN', 5, 1, '', 'center')],
                                             [('3.', 1, 1, '', 'center'), ('PRODUCT NO.', 2, 1, '', 'left'), ('T 1070101', 5, 1, '', 'center'),
                                              ('2.', 1, 1, '', 'center'), ('FRAME', 1, 1, '', 'center'), ('315 SC', 4, 1, '', 'center')],
                                             [('4.', 1, 1, '', 'center'), ('TOTAL HEAD', 2, 1, '', 'left'), ('16.2', 3, 1, '', 'center'),
                                              ('M', 2, 1, '', 'center'), ('3.', 1, 1, '', 'center'), ('FREQUENCY', 1, 1, '', 'center'),
                                              ('50', 3, 1, '', 'center'), ('HZ', 1, 1, '', 'center')],
                                             [('5.', 1, 1, '', 'center'), ('SPEED', 2, 1, '', 'left'), ('890', 3, 1, '', 'center'),
                                              ('RPM', 2, 1, '', 'center'), ('4.', 1, 1, '', 'center'), ('SPEED', 1, 1, '', 'center'),
                                              ('975', 3, 1, '', 'center'), ('RPM', 1, 1, '', 'center')],
                                             [('6.', 1, 2, '', 'center'), ('CAPACITY', 2, 2, '', 'left'), ('( 2 UNIT ) 2 X 50%', 5, 1, '', 'center'),
                                              ('5.', 1, 2, '', 'center'), ('OUTPUT', 1, 2, '', 'center'), ('125', 3, 1, '', 'center'),
                                              ('HP', 1, 1, '', 'center')],
                                             [('1375', 3, 1, '', 'center'), ('M3/H', 2, 1, '', 'center'), ('90', 3, 1, '', 'center'),
                                              ('KW', 1, 1, '', 'center')],
                                             [('7.', 1, 1, '', 'center'), ('DRIVER', 2, 1, '', 'left'), ('90', 3, 1, '', 'center'),
                                              ('KW', 2, 1, '', 'center'), ('6.', 1, 1, '', 'center'), ('VOLTAGE', 1, 1, '', 'center'),
                                              ('380 - 415', 3, 1, '', 'center'), ('VOLT', 1, 1, '', 'center')],
                                             [('8.', 1, 2, '', 'center'), ('BEARING NO.', 2, 2, '', 'left'), ('FRONT', 2, 1, '', 'center'),
                                              ('6315 C3', 2, 1, '', 'center'), ('1 PCS', 1, 1, '', 'center'), ('7.', 1, 1, '', 'center'),
                                              ('CURRENT', 1, 1, '', 'center'), ('170', 3, 1, '', 'center'), ('AMPERE', 1, 1, '', 'center')],
                                             [('REAR', 2, 1, '', 'center'), ('6315 C3', 2, 1, '', 'center'), ('1 PCS', 1, 1, '', 'center'),
                                              ('8.', 1, 1, '', 'center'), ('BEARINGS', 1, 1, '', 'center'), ('6315 / NU 320C3', 4, 1, '', 'center')],
                                             [('9.', 1, 1, '', 'center'), ('DATE', 2, 1, '', 'left'), ('OCT 2019', 5, 1, '', 'center'),
                                              ('9.', 1, 1, '', 'center'), ('SER. NO', 1, 1, '', 'center'), ('9106304003', 4, 1, '', 'center')],
                                             [('10.', 1, 1, '', 'center'), ('PRODUCT', 2, 1, '', 'left'),
                                              ('TORISHIMA GUNA INDONESIA', 5, 1, '', 'center'), ('10.', 1, 1, '', 'center'),
                                              ('WEIGHT', 1, 1, '', 'center'), ('839', 3, 1, '', 'center'), ('KG', 1, 1, '', 'center')],
                                             [('DESIGN PUMP', 8, 2, 'b', 'center'), ('11.', 1, 1, '', 'center'), ('DATE', 1, 1, '', 'center'),
                                              ('2019', 4, 1, '', 'center')],
                                             [('12.', 1, 1, '', 'center'), ('PRODUCT', 1, 1, '', 'center'),
                                              ('TECO ELEC & MACH. PTE. LTD', 4, 1, '', 'center')],
                                             [('KKS', 3, 1, '', 'left'), ('AP / 1103 A/B', 5, 1, '', 'center'), ('LUBRICATION', 6, 2, 'b', 'center')],
                                             [('FLUID', 3, 1, '', 'left'), ('SEA WATER', 5, 1, '', 'center')],
                                             [('SUCTION PRESSURE', 3, 1, '', 'left'), ('0.1', 3, 1, '', 'center'), ('KG/CM2 G', 2, 1, '', 'center'),
                                              ('1.', 1, 3, '', 'center'), ('KIND OF GREASE', 1, 3, '', 'center'),
                                              ('MULTEMP. SRL OR EQUIVALENT GREASE', 4, 2, '', 'center')],
                                             [('DISCHARGE PRESSURE', 3, 1, '', 'left'), ('1.72', 3, 1, '', 'center'),
                                              ('KG/CM2 G', 2, 1, '', 'center')],
                                             [('DIFFERENTIAL PRESSURE', 3, 1, '', 'left'), ('1.62', 3, 1, '', 'center'),
                                              ('KG/CM2 G', 2, 1, '', 'center'), ('( DO NOT MIX WITH OTHER GREASE )', 4, 1, '', 'center')],
                                             [('SYSTEM', 3, 1, '', 'center'), ('SEA WATER COOLING SUPPLY SYSTEM', 5, 1, '', 'center'),
                                              ('2.', 1, 1, '', 'center'), ('RE - LUBRICATED PERIOD', 1, 1, '', 'center'),
                                              ('EVERY 3000 HOURS', 4, 1, '', 'center')],
                                             [('DRAWING NO.', 3, 3, '', 'center'), ('1802 - 00 - 10 - P - 001 - 01', 5, 1, '', 'center'),
                                              ('3.', 1, 2, '', 'center'), ('QUANTITY', 1, 2, '', 'center'), ('DRIVE END', 3, 1, '', 'center'),
                                              ('160 GR', 1, 1, '', 'center')],
                                             [('1803 - 00 - 10 - P - 001 - 02', 5, 2, '', 'center'), ('NON DRIVE END', 3, 1, '', 'center'),
                                              ('100 GR', 1, 1, '', 'center')],
                                             [('4.', 1, 1, '', ''), ('ADD GREASE AT THE BEGINNING OF FIRST OPERATION', 5, 1, '', 'center')]],
                                            [4.68, 5.67, 10.89, 2.7, 6.03, 8.37, 4.5, 6.21, 4.68, 16.74, 2.7, 6.03, 6.03, 14.76]),
                                           ('images', ['s07_1.jpg', 's07_2.jpg']),
                                           ('table',
                                            [[('BEARING SPECIFICATION', 6, 1, 'b', 'center'),
                                              ('TYPE : 6315 CE SINGLE ROW GROOVE', 8, 1, 'b', 'center')],
                                             [('1.', 1, 1, '', 'center'), ('BRAND', 3, 1, '', ''), ('SKF', 4, 1, '', 'left'), (None, 6, 1, '', '')],
                                             [('2.', 1, 1, '', 'center'), ('TYPE', 3, 1, '', ''), ('6315 C3', 4, 1, '', 'left'),
                                              (None, 6, 1, '', '')],
                                             [('3.', 1, 1, '', 'center'), ('INSIDE DIAMETER', 3, 1, '', ''), ('75 MM', 4, 1, '', 'left'),
                                              (None, 6, 1, '', '')],
                                             [('4.', 1, 1, '', 'center'), ('OUTSIDE DIAMETER', 3, 1, '', ''), ('160 MM', 4, 1, '', 'left'),
                                              (None, 6, 1, '', '')],
                                             [('5.', 1, 1, '', 'center'), ('WIDTH', 3, 1, '', ''), ('37 MM', 4, 1, '', 'left'), (None, 6, 1, '', '')],
                                             [('6.', 1, 1, '', 'center'), ('CLEARANCE', 3, 1, '', ''), ('C3', 4, 1, '', 'left'),
                                              (None, 6, 1, '', '')],
                                             [('7.', 1, 1, '', 'center'), ('MODEL', 3, 1, '', ''), ('SINGLE ROW DEEP GROOVE', 4, 1, '', 'left'),
                                              (None, 6, 1, '', '')],
                                             [('8.', 1, 1, '', 'center'), ('PRICE ( 2013 )', 3, 1, '', ''), ('£ 91,93', 4, 1, '', 'left'),
                                              (None, 6, 1, '', '')]],
                                            [4.68, 5.67, 10.89, 2.7, 6.03, 8.37, 4.5, 6.21, 4.68, 16.74, 2.7, 6.03, 6.03, 14.76])]},
 '8. CONDENSATE PUMP': {'name': 'CONDENSATE FEED WATER PUMP',
                        'info': {'Unit': '2', 'No. Formulir': '1', 'Tanggal': '19 - 01 - 2013', 'Halaman': '1'},
                        'col_pct': [4.54, 7.89, 9.17, 6.61, 9.17, 4.93, 4.63, 5.13, 15.59, 2.96, 6.61, 6.61, 16.17],
                        'segments': [('table',
                                      [[('SPECIFICATION', 13, 1, 'b', 'center')],
                                       [('NO.', 1, 1, 'b', ''), ('PUMP', 6, 1, 'b', 'center'), ('NO.', 1, 1, 'b', ''),
                                        ('MOTOR', 5, 1, 'b', 'center')],
                                       [('1.', 1, 1, '', 'center'), ('TYPE', 2, 1, '', 'center'), ('4 N6 ( HORIZONTAL PUMP )', 4, 1, '', ''),
                                        ('1.', 1, 1, '', 'center'), ('FRAME', 1, 1, '', 'center'), ('Y2-180M - 2', 4, 1, '', 'center')],
                                       [('2.', 1, 3, '', 'center'), ('CAPACITY', 2, 3, '', 'center'), ('50', 1, 1, '', ''), (None, 1, 1, '', ''),
                                        ('M3/H', 2, 1, '', 'center'), ('2.', 1, 1, '', 'center'), ('SPEED', 1, 1, '', 'center'),
                                        ('2940', 3, 1, '', 'center'), ('RPM', 1, 1, '', 'center')],
                                       [('13.9', 2, 1, '', ''), ('L/S', 2, 1, '', 'center'), ('3.', 1, 2, '', 'center'),
                                        ('OUTPUT', 1, 2, '', 'center'), ('22', 3, 1, '', 'center'), ('KW', 1, 1, '', 'center')],
                                       [('2 UNIT ( 2 X 100 )', 4, 1, '', ''), ('29.5', 3, 1, '', 'center'), ('HP', 1, 1, '', 'center')],
                                       [('3.', 1, 1, '', 'center'), ('TOTAL HEAD', 2, 1, '', 'center'), ('59.5', 2, 1, '', ''),
                                        ('M', 2, 1, '', 'center'), ('4.', 1, 1, '', 'center'), ('VOLTAGE', 1, 1, '', 'center'),
                                        ('380', 3, 1, '', 'center'), ('VOLT', 1, 1, '', 'center')],
                                       [('4.', 1, 1, '', 'center'), ('SPEED', 2, 1, '', 'center'), ('2950', 1, 1, '', ''), (None, 1, 1, '', ''),
                                        ('RPM', 2, 1, '', 'center'), ('5.', 1, 1, '', 'center'), ('CURRENT', 1, 1, '', 'center'),
                                        ('41.0', 3, 1, '', 'center'), ('AMPERE', 1, 1, '', 'center')],
                                       [('5.', 1, 1, '', 'center'), ('DRIVER', 2, 1, '', 'center'), ('14.1', 2, 1, '', ''),
                                        ('KW', 2, 1, '', 'center'), ('6.', 1, 1, '', 'center'), ('PF', 1, 1, '', 'center'),
                                        ('0.90', 4, 1, '', 'center')],
                                       [('6.', 1, 1, '', 'center'), ('PUMP EFF.', 2, 1, '', 'center'), ('57.5', 2, 1, '', ''),
                                        ('%', 2, 1, '', 'center'), ('7.', 1, 1, '', 'center'), ('EFF.', 1, 1, '', 'center'),
                                        ('90.5', 3, 1, '', 'center'), ('%', 1, 1, '', 'center')],
                                       [('7.', 1, 1, '', 'center'), ('NPSH', 2, 1, '', 'center'), ('1.75', 2, 1, '', ''), ('M', 2, 1, '', 'center'),
                                        ('8.', 1, 1, '', 'center'), ('SER. NO.', 1, 1, '', 'center'), ('JB/T 8680.1 - 1998', 4, 1, '', 'center')],
                                       [('8.', 1, 1, '', 'center'), ('IMPELLER DIM.', 2, 1, '', 'center'), ('225', 1, 1, '', ''),
                                        (None, 1, 1, '', ''), ('MM', 2, 1, '', 'center'), ('9.', 1, 2, '', 'center'), ('PRODUCT', 1, 2, '', 'center'),
                                        ('SHANDONG HUALI ELECTRIC MOTOR GROUP.CO.LTD', 4, 2, '', 'center')],
                                       [('9.', 1, 1, '', 'center'), ('WEIGHT', 2, 1, '', 'center'), ('94', 1, 1, '', ''), (None, 1, 1, '', ''),
                                        ('KG', 2, 1, '', 'center')],
                                       [('10.', 1, 1, '', 'center'), ('CUSTOMER', 1, 1, '', 'center'),
                                        ('SHANDONG MACHINERY I&E GROUP CORPORATION', 5, 1, '', 'center'), ('DESIGN PUMP', 6, 1, 'b', 'center')],
                                       [('11.', 1, 2, '', 'center'), ('MANUFACTURER', 1, 2, '', 'center'),
                                        ('SHENYANG PUMP MANUFACTORY', 5, 2, '', 'center'), ('KKS NO.', 2, 1, '', 'left'),
                                        ('AP - 1101 A/B/C/D', 4, 1, '', 'center')],
                                       [('FLUID', 2, 1, '', 'left'), ('CONDENSATE', 4, 1, '', 'center')],
                                       [('SYSTEM', 2, 1, '', 'center'), ('STEAM SUPPLY & SYSTEM', 5, 1, '', 'center'),
                                        ('SUCTION PRESSURE', 2, 1, '', 'left'), ('0.085', 3, 1, '', 'center'), ('BAR', 1, 1, '', 'center')],
                                       [('DRAWING NO.', 2, 2, '', 'center'), ('1802 - 00 - M - 10 - LB - 003 - 05', 5, 2, '', 'center'),
                                        ('DISCHARGE PRESSURE', 2, 1, '', 'center'), ('7', 3, 1, '', 'center'), ('BAR', 1, 1, '', 'center')],
                                       [('DIFFERENTIAL PRESS.', 2, 1, '', 'center'), ('HOLD', 4, 1, '', 'center')]],
                                      [4.54, 7.89, 9.17, 6.61, 9.17, 4.93, 4.63, 5.13, 15.59, 2.96, 6.61, 6.61, 16.17]),
                                     ('images', ['s08_1.jpg'])]},
 '9. GENERATOR COOLER': {'name': 'GENERATOR COOLER',
                         'info': {},
                         'col_pct': [4.99, 7.68, 11.04, 6.43, 8.93, 4.8, 4.51, 4.99, 15.17, 2.88, 6.43, 6.43, 15.74],
                         'segments': [('table',
                                       [[('MAIN DATA OF THE COOLER', 13, 1, 'b', 'center')],
                                        [('NO.', 1, 1, 'b', 'center'), ('DESCRIPTIONS', 7, 1, 'b', 'center'), ('VALUE', 3, 1, 'b', 'center'),
                                         ('UNITS', 2, 1, 'b', 'center')],
                                        [('1.', 1, 1, '', 'center'), ('CAPACITY OF HEAT TRANSFER', 7, 1, '', 'left'), ('90', 3, 1, '', 'center'),
                                         ('KW', 2, 1, '', 'center')],
                                        [('2.', 1, 1, '', 'center'), ('SPEED OF THE COOLING AIR', 7, 1, '', 'left'), ('3.35', 3, 1, '', 'center'),
                                         ('M3/S', 2, 1, '', 'center')],
                                        [('3.', 1, 1, '', 'center'), ('SPEED OF THE COOLING WATER', 7, 1, '', 'left'), ('25', 3, 1, '', 'center'),
                                         ('M3/S', 2, 1, '', 'center')],
                                        [('4.', 1, 1, '', 'center'), ('INLET WATER PRESSURE', 7, 1, '', 'left'), ('0.2', 3, 1, '', 'center'),
                                         ('MPA', 2, 1, '', 'center')],
                                        [('5.', 1, 1, '', 'center'), ('PRESSURE DROP OF THE WATER', 7, 1, '', 'left'), ('5187', 3, 1, '', 'center'),
                                         ('PA', 2, 1, '', 'center')],
                                        [('6.', 1, 1, '', 'center'), ('NUMBER OF THE WATER CIRCUITS', 7, 1, '', 'left'), ('2', 3, 1, '', 'center'),
                                         ('PA', 2, 1, '', 'center')],
                                        [('7.', 1, 1, '', 'center'), ('PRESSURE DROP OF THE AIR', 7, 1, '', 'left'), ('300', 3, 1, '', 'center'),
                                         ('PA', 2, 1, '', 'center')],
                                        [('8.', 1, 1, '', 'center'), ('TEMPERATURE OF THE INLET WATER', 7, 1, '', 'left'), ('33', 3, 1, '', 'center'),
                                         ('°C', 2, 1, '', 'center')],
                                        [('9.', 1, 1, '', 'center'), ('TEMPERATURE OF THE COOLING AIR', 7, 1, '', 'left'), ('40', 3, 1, '', 'center'),
                                         ('°C', 2, 1, '', 'center')],
                                        [('10.', 1, 1, '', 'center'), ('CONNECTION STYLE OF THE WATER CIRCUITS', 7, 1, '', 'left'),
                                         ('PARALLEL CONNECTED', 3, 1, '', 'center'), (None, 2, 1, '', '')],
                                        [('11.', 1, 1, '', 'center'), ('KIND OF THE COOLING WATER', 7, 1, '', 'left'),
                                         ('SEA WATER', 3, 1, '', 'center'), (None, 2, 1, '', '')],
                                        [('12.', 1, 1, '', 'center'), ('MATERIAL OF THE COOLING PIPE', 7, 1, '', 'left'), ('B10', 3, 1, '', 'center'),
                                         (None, 2, 1, '', '')],
                                        [('13.', 1, 1, '', 'center'), ('MATERIAL OF FRAME/CASING', 7, 1, '', 'left'),
                                         ('ALL MATERIAL WHICH DIRECT CONTACT WITH THE SEA WATER IS SUS 304L', 3, 1, '', 'center'),
                                         (None, 2, 1, '', '')],
                                        [('14.', 1, 1, '', 'center'), ('TEST PRESSURE', 7, 1, '', 'left'), ('0.6', 3, 1, '', 'center'),
                                         ('MPA', 2, 1, '', 'center')],
                                        [('15.', 1, 1, '', 'center'), ('PRODUCT', 7, 1, '', 'left'),
                                         ('SHANDONG MACHINERY I&E GROUP CORPORATION', 3, 1, '', 'center'), (None, 2, 1, '', '')]],
                                       [4.99, 7.68, 11.04, 6.43, 8.93, 4.8, 4.51, 4.99, 15.17, 2.88, 6.43, 6.43, 15.74]),
                                      ('images', ['s09_1.jpg', 's09_2.jpg'])]},
 '10. DEMIN PUMP': {'name': 'DEMIN PUMP',
                    'info': {},
                    'col_pct': [4.63, 7.22, 6.86, 7.22, 5.97, 8.29, 4.45, 8.65, 3.83, 14.08, 2.67, 5.97, 3.56, 16.58],
                    'segments': [('table',
                                  [[('SPECIFICATION', 14, 1, 'b', 'center')],
                                   [('NO.', 1, 1, 'b', ''), ('PUMP', 7, 1, 'b', 'center'), ('NO.', 1, 1, 'b', ''), ('MOTOR', 5, 1, 'b', 'center')],
                                   [('1.', 1, 1, '', 'center'), ('MEREK', 3, 1, '', 'left'), ('TORISHIMA PUMP', 4, 1, '', 'left'),
                                    ('1.', 1, 1, '', 'center'), ('MEREK', 2, 1, '', 'left'), ('TECO. ELEC. & MACH. PTE. LTD', 3, 1, '', 'left')],
                                   [('2.', 1, 1, '', 'center'), ('TYPE & SIZE', 3, 1, '', 'left'), ('CPEN 25 - 160', 4, 1, '', 'left'),
                                    ('2.', 1, 1, '', 'center'), ('TECO', 2, 1, '', 'left'), ('3 PHASE - INDUCTION', 3, 1, '', 'left')],
                                   [('3.', 1, 1, '', 'center'), ('PRODUCT NO.', 3, 1, '', 'left'), ('T 1080446', 4, 1, '', 'left'),
                                    ('3.', 1, 1, '', 'center'), ('2 POLE', 2, 1, '', 'left'), ('50', 1, 1, '', 'left'), ('HZ', 2, 1, '', '')],
                                   [('4.', 1, 1, '', 'center'), ('TOTAL HEAD', 3, 1, '', 'left'), ('35', 1, 1, '', 'left'), ('M', 3, 1, '', 'left'),
                                    ('4.', 1, 2, '', 'center'), ('OUTPUT', 2, 2, '', 'left'), ('3', 1, 1, '', 'left'), ('HP', 2, 1, '', 'left')],
                                   [('5.', 1, 1, '', 'center'), ('CAPACITY', 3, 1, '', 'left'), ('4', 1, 1, '', 'left'), ('M3/H', 1, 1, '', ''),
                                    ('2 X 100%', 2, 1, '', 'center'), ('2.2', 1, 1, '', 'left'), ('KW', 2, 1, '', 'left')],
                                   [('6.', 1, 1, '', 'center'), ('SPEED', 3, 1, '', 'left'), ('2900', 1, 1, '', 'left'), ('RPM', 3, 1, '', 'left'),
                                    ('5.', 1, 1, '', 'center'), ('VOLT', 2, 1, '', 'left'), ('380', 2, 1, '', 'left'), ('VOLT', 1, 1, '', '')],
                                   [('7.', 1, 1, '', 'center'), ('DRIVER', 3, 1, '', 'left'), ('2.2', 1, 1, '', 'left'), ('KW', 3, 1, '', 'left'),
                                    ('6.', 1, 1, '', 'center'), ('CURRENT', 2, 1, '', 'left'), ('4.5', 1, 1, '', 'left'),
                                    ('AMPERE', 2, 1, '', 'left')],
                                   [('8.', 1, 2, '', 'center'), ('BEARING NO.', 3, 2, '', 'left'), ('FRONT', 1, 1, '', 'left'),
                                    ('6305 DDU C3', 2, 1, '', 'center'), ('1 PCS', 1, 1, '', 'left'), ('7.', 1, 2, '', 'center'),
                                    ('BEARING NO.', 2, 2, '', 'left'), ('FRONT', 1, 1, '', ''), ('6205 ZZ', 2, 1, '', 'center')],
                                   [('REAR', 1, 1, '', 'left'), ('6305 DDU C3', 2, 1, '', 'center'), ('1 PCS', 1, 1, '', 'left'),
                                    ('REAR', 1, 1, '', ''), ('6205 ZZ', 2, 1, '', 'center')],
                                   [('9.', 1, 1, '', 'center'), ('DELIVERY TIME', 3, 1, '', 'left'), ('OCT 2010', 4, 1, '', 'left'),
                                    ('8.', 1, 1, '', 'center'), ('SPEED', 2, 1, '', 'left'), ('2870', 1, 1, '', 'left'), ('RPM', 2, 1, '', 'left')],
                                   [('PUMP DESIGN', 8, 2, 'b', 'center'), ('9.', 1, 1, '', 'center'), ('SER. NO', 2, 1, '', 'left'),
                                    ('P2104334085', 3, 1, '', 'left')],
                                   [('10.', 1, 2, '', 'center'), ('FAN BLADE', 2, 2, '', 'left'), ('TYPE', 1, 1, '', ''),
                                    ('180 L.C', 2, 1, '', 'left')],
                                   [('KKS NO.', 3, 1, '', 'left'), (None, 5, 1, '', ''), ('NO.', 1, 1, '', ''), ('31402 C103', 2, 1, '', 'left')],
                                   [('NO.', 3, 1, '', 'left'), ('2 UNIT ( 2 X 100% )', 5, 1, '', 'left'), ('11.', 1, 1, '', 'center'),
                                    ('AMB. TEMP', 2, 1, '', 'left'), ('40', 1, 1, '', 'left'), ('°C', 2, 1, '', 'left')],
                                   [('SUCTION PRESSURE', 3, 1, '', 'left'), (None, 2, 1, '', ''), ('KG/CM2 G', 3, 1, '', 'center'),
                                    ('12.', 1, 1, '', 'center'), ('FRAME SIZE', 2, 1, '', 'left'), ('90 L', 3, 1, '', 'left')],
                                   [('DISCHARGE PRESSURE', 3, 1, '', 'left'), (None, 2, 1, '', ''), ('KG/CM2 G', 3, 1, '', 'center'),
                                    ('SYSTEM', 2, 1, '', 'center'), (None, 4, 1, '', '')],
                                   [('DIFFERENTIAL PRESS.', 3, 1, '', 'left'), (None, 2, 1, '', ''), ('KG/CM2 G', 3, 1, '', 'center'),
                                    ('DRAWING NO.', 2, 1, '', 'center'), (None, 4, 1, '', '')]],
                                  [4.63, 7.22, 6.86, 7.22, 5.97, 8.29, 4.45, 8.65, 3.83, 14.08, 2.67, 5.97, 3.56, 16.58]),
                                 ('images', ['s10_1.jpg', 's10_2.jpg']),
                                 ('table',
                                  [[('BEARING SPECIFICATION', 6, 1, 'b', 'center'),
                                    ('TYPE : 6305 DDU KOYO DEEP GROOVE BEARING', 8, 1, 'b', 'center')],
                                   [('1.', 1, 1, '', 'center'), ('BRAND', 3, 1, '', ''), ('KOYO', 10, 1, '', '')],
                                   [('2.', 1, 1, '', 'center'), ('TYPE', 3, 1, '', ''), ('6305 DDU C3', 10, 1, '', '')],
                                   [('3.', 1, 1, '', 'center'), ('INSIDE DIAMETER', 3, 1, '', ''), ('25 MM', 10, 1, '', '')],
                                   [('4.', 1, 1, '', 'center'), ('OUTSIDE DIAMETER', 3, 1, '', ''), ('62 MM', 10, 1, '', '')],
                                   [('5.', 1, 1, '', 'center'), ('WIDTH', 3, 1, '', ''), ('17 MM', 10, 1, '', '')],
                                   [('6.', 1, 1, '', 'center'), ('CLEARANCE', 3, 1, '', ''), ('C3', 10, 1, '', '')],
                                   [('7.', 1, 1, '', 'center'), ('MODEL', 3, 1, '', ''), ('TWO RUBBER SEALS ( 2RS )', 10, 1, '', '')],
                                   [('8.', 1, 1, '', 'center'), ('PRICE ( 2013 )', 3, 1, '', ''), ('£ 8.30', 1, 1, '', ''),
                                    ('£ 8.30', 9, 1, '', '')]],
                                  [4.63, 7.22, 6.86, 7.22, 5.97, 8.29, 4.45, 8.65, 3.83, 14.08, 2.67, 5.97, 3.56, 16.58])]},
 '11. RO PUMP': {'name': 'REVERSE OSMOSIS TRANSFER PUMP',
                 'info': {},
                 'col_pct': [4.96, 6.94, 14.07, 0.36, 6.04, 8.39, 4.51, 6.67, 3.88, 14.25, 2.7, 6.04, 3.6, 17.59],
                 'segments': [('table',
                               [[('SPECIFICATION', 14, 1, 'b', 'center')],
                                [('NO.', 1, 1, 'b', ''), ('PUMP', 7, 1, 'b', 'center'), ('NO.', 1, 1, 'b', ''), ('MOTOR', 5, 1, 'b', 'center')],
                                [('1.', 1, 1, '', 'center'), ('MEREK', 2, 1, '', 'left'), (None, 1, 1, '', ''), ('TORISHIMA PUMP', 4, 1, '', 'left'),
                                 ('1.', 1, 1, '', 'center'), ('MEREK', 2, 1, '', 'left'), ('TECO. ELEC. & MACH. PTE. LTD', 3, 1, '', 'left')],
                                [('2.', 1, 1, '', 'center'), ('TYPE & SIZE', 2, 1, '', 'left'), (None, 1, 1, '', ''),
                                 ('FTA - N 65 X 50 - 200', 4, 1, '', 'left'), ('2.', 1, 1, '', 'center'), ('TECO', 2, 1, '', 'left'),
                                 ('AEEBKBO20010FMB', 3, 1, '', 'left')],
                                [('3.', 1, 1, '', 'center'), ('PRODUCT NO.', 2, 1, '', 'left'), (None, 1, 1, '', ''),
                                 ('TS 1018512', 4, 1, '', 'left'), ('3.', 1, 1, '', 'center'), ('4 POLE', 2, 1, '', 'left'), ('50', 1, 1, '', 'left'),
                                 ('HZ', 2, 1, '', '')],
                                [('4.', 1, 1, '', 'center'), ('TOTAL HEAD', 2, 1, '', 'left'), (None, 1, 1, '', ''), ('40', 1, 1, '', 'left'),
                                 ('M', 3, 1, '', 'left'), ('4.', 1, 2, '', 'center'), ('OUTPUT', 2, 2, '', 'left'), ('10', 1, 1, '', 'left'),
                                 ('HP', 2, 1, '', 'left')],
                                [('5.', 1, 1, '', 'center'), ('CAPACITY', 2, 1, '', 'left'), (None, 1, 1, '', ''), ('27.5', 1, 1, '', 'left'),
                                 ('M3/H', 1, 1, '', ''), ('2 X 100%', 2, 1, '', 'center'), ('7.5', 1, 1, '', 'left'), ('KW', 2, 1, '', 'left')],
                                [('6.', 1, 1, '', 'center'), ('SPEED', 2, 1, '', 'left'), (None, 1, 1, '', ''), ('2900', 1, 1, '', 'left'),
                                 ('RPM', 3, 1, '', 'left'), ('5.', 1, 1, '', 'center'), ('VOLT', 2, 1, '', 'left'), ('380 - 415', 2, 1, '', 'left'),
                                 ('VOLT', 1, 1, '', '')],
                                [('7.', 1, 1, '', 'center'), ('DRIVER', 2, 1, '', 'left'), (None, 1, 1, '', ''), ('7.5', 1, 1, '', 'left'),
                                 ('KW', 3, 1, '', 'left'), ('6.', 1, 1, '', 'center'), ('CURRENT', 2, 1, '', 'left'), ('13.8', 1, 1, '', 'left'),
                                 ('AMPERE', 2, 1, '', 'left')],
                                [('8.', 1, 2, '', 'center'), ('BEARING NO.', 2, 2, '', 'left'), (None, 1, 1, '', ''), ('FRONT', 1, 1, '', 'left'),
                                 ('6305 DDU C3', 2, 1, '', 'center'), ('1 PCS', 1, 1, '', 'left'), ('7.', 1, 2, '', 'center'),
                                 ('BEARING NO.', 2, 2, '', 'left'), ('FRONT', 1, 1, '', ''), ('6308 ZZ', 2, 1, '', 'center')],
                                [(None, 1, 1, '', ''), ('REAR', 1, 1, '', 'left'), ('6305 DDU C3', 2, 1, '', 'center'), ('1 PCS', 1, 1, '', 'left'),
                                 ('REAR', 1, 1, '', ''), ('6308 ZZ', 2, 1, '', 'center')],
                                [('9.', 2, 1, '', 'center'), ('DELIVERY TIME', 2, 1, '', ''), ('JUL 2019', 4, 1, '', 'left'),
                                 ('8.', 1, 1, '', 'center'), ('SPEED', 2, 1, '', 'left'), ('2880', 1, 1, '', 'left'), ('RPM', 2, 1, '', 'left')],
                                [('PUMP DESIGN', 8, 2, 'b', 'center'), ('9.', 1, 1, '', 'center'), ('SER. NO', 2, 1, '', 'left'),
                                 ('H4103025 037', 3, 1, '', 'left')],
                                [('10.', 1, 2, '', 'center'), ('FAN BLADE', 2, 2, '', 'left'), ('TYPE', 3, 1, '', '')],
                                [('KKS NO.', 3, 1, '', 'left'), (None, 5, 1, '', ''), ('NO.', 3, 1, '', '')],
                                [('NO.', 3, 1, '', 'left'), ('2 UNIT ( 2 X 100% )', 5, 1, '', 'left'), ('11.', 1, 1, '', 'center'),
                                 ('AMB. TEMP', 2, 1, '', 'left'), ('40', 1, 1, '', 'left'), ('°C', 2, 1, '', 'left')],
                                [('SUCTION PRESSURE', 3, 1, '', 'left'), (None, 2, 1, '', ''), ('KG/CM2 G', 3, 1, '', 'center'),
                                 ('12.', 1, 1, '', 'center'), ('FRAME SIZE', 2, 1, '', 'left'), ('F 132 S', 3, 1, '', 'left')],
                                [('DISCHARGE PRESSURE', 3, 1, '', 'left'), (None, 2, 1, '', ''), ('KG/CM2 G', 3, 1, '', 'center'),
                                 ('SYSTEM', 2, 1, '', 'center'), (None, 4, 1, '', '')],
                                [('DIFFERENTIAL PRESS.', 3, 1, '', 'left'), (None, 2, 1, '', ''), ('KG/CM2 G', 3, 1, '', 'center'),
                                 ('DRAWING NO.', 2, 1, '', 'center'), (None, 4, 1, '', '')]],
                               [4.96, 6.94, 14.07, 0.36, 6.04, 8.39, 4.51, 6.67, 3.88, 14.25, 2.7, 6.04, 3.6, 17.59]),
                              ('images', ['s11_1.jpg', 's11_2.jpg', 's11_3.jpg', 's11_4.jpg', 's11_5.jpg']),
                              ('table', [[('TYPE : MECH SEAL CN25 (22-MG1/25-S1) SILICAR/SILICAR/VITON/SS316', 14, 1, 'b', 'center')]],
                               [4.96, 6.94, 14.07, 0.36, 6.04, 8.39, 4.51, 6.67, 3.88, 14.25, 2.7, 6.04, 3.6, 17.59]),
                              ('table', [[('BEARING SPECIFICATION', 6, 1, 'b', 'center')]], [12.17, 17.04, 34.51, 0.88, 14.82, 20.57]),
                              ('table',
                               [[('1.', 1, 1, '', 'center'), ('BRAND', 4, 1, '', ''), ('KOYO', 9, 1, '', '')],
                                [('2.', 1, 1, '', 'center'), ('TYPE', 4, 1, '', ''), ('6305 DDU C3', 9, 1, '', '')],
                                [('3.', 1, 1, '', 'center'), ('INSIDE DIAMETER', 4, 1, '', ''), ('25 MM', 9, 1, '', '')],
                                [('4.', 1, 1, '', 'center'), ('OUTSIDE DIAMETER', 4, 1, '', ''), ('62 MM', 9, 1, '', '')],
                                [('5.', 1, 1, '', 'center'), ('WIDTH', 4, 1, '', ''), ('17 MM', 9, 1, '', '')],
                                [('6.', 1, 1, '', 'center'), ('CLEARANCE', 4, 1, '', ''), ('C3', 9, 1, '', '')],
                                [('7.', 1, 1, '', 'center'), ('MODEL', 4, 1, '', ''), ('TWO RUBBER SEALS ( 2RS )', 9, 1, '', '')],
                                [('8.', 1, 1, '', 'center'), ('PRICE ( 2013 )', 4, 1, '', ''), ('£ 8.30', 9, 1, '', '')]],
                               [4.96, 6.94, 14.07, 0.36, 6.04, 8.39, 4.51, 6.67, 3.88, 14.25, 2.7, 6.04, 3.6, 17.59]),
                              ('table',
                               [[('INSPECTION REPORT', 3, 1, 'b', 'center')],
                                [('EQUIPMENT', 1, 1, '', ''), (':', 1, 1, '', 'center'), ('RO PUMP #1 & #2', 1, 1, '', '')],
                                [('DATE', 1, 1, '', ''), (':', 1, 1, '', 'center'), ('25-09-2013', 1, 1, '', 'left')],
                                [('PERIHAL', 1, 1, '', ''), (':', 1, 1, '', 'center'), ('KEBOCORAN POMPA', 1, 1, '', '')],
                                [('ANALISIS DAN TROUBLE', 3, 1, 'b', 'center')],
                                [('INDIKASI MASALAH', 1, 2, '', 'left'), (None, 1, 1, '', ''),
                                 ('KEBOCORAN PADA SEAL POMPA, SEHINGGA AIR KELUAR DARI', 1, 1, '', '')],
                                [(None, 1, 1, '', ''), ('CASING POMPA', 1, 1, '', '')],
                                [('MATERIAL YANG BERMASALAH', 2, 1, '', 'left'), ('MECHANICAL SEAL PUMP', 1, 1, '', '')],
                                [('TEMUAN MASALAH', 2, 1, '', 'left'), ('BOCOR PADA MECHANICAL SEAL', 1, 1, '', '')],
                                [('SOLUTION', 2, 1, '', 'left'), ('PENGGANTIAN MECHANICAL SEAL', 1, 1, '', '')]],
                               [33.89, 3.37, 62.74]),
                              ('table',
                               [[('TG. BALAI KARIMUN, TGL. 25 SEPTEMBER 2013', 1, 1, '', 'center')],
                                [('TIM HAR TURBIN & AUXILIARY', 1, 1, '', 'center')], [('SUGANDA TOBING', 1, 1, '', 'center')]],
                               [100.0])]},
 '12. MAKE UP PUMP CT': {'name': 'MAKE UP TRANSFER PUMP',
                         'info': {},
                         'col_pct': [5.07, 6.6, 8.71, 2.87, 6.41, 8.9, 4.78, 5.65, 4.11, 15.12, 2.87, 6.41, 3.82, 18.66],
                         'segments': [('table',
                                       [[('SPECIFICATION', 14, 1, 'b', 'center')],
                                        [('NO.', 1, 1, 'b', ''), ('PUMP', 7, 1, 'b', 'center'), ('NO.', 1, 1, 'b', ''),
                                         ('MOTOR', 5, 1, 'b', 'center')],
                                        [('1.', 1, 1, '', 'center'), ('MEREK', 3, 1, '', 'left'), ('TORISHIMA PUMP', 4, 1, '', 'left'),
                                         ('1.', 1, 1, '', 'center'), ('MEREK', 2, 1, '', 'left'),
                                         ('TECO. ELEC. & MACH. PTE. LTD', 3, 1, '', 'left')],
                                        [('2.', 1, 1, '', 'center'), ('TYPE & SIZE', 3, 1, '', 'left'), ('FTA - N 150 X 125 - 315', 4, 1, '', 'left'),
                                         ('2.', 1, 1, '', 'center'), ('TECO', 2, 1, '', 'left'), ('AEEBKBD40040 FMB', 3, 1, '', 'left')],
                                        [('3.', 1, 1, '', 'center'), ('PRODUCT NO.', 3, 1, '', 'left'), ('TS 1018510', 4, 1, '', 'left'),
                                         ('3.', 1, 1, '', 'center'), ('2 POLE', 2, 1, '', 'left'), ('50', 1, 1, '', 'left'), ('HZ', 2, 1, '', '')],
                                        [('4.', 1, 1, '', 'center'), ('TOTAL HEAD', 3, 1, '', 'left'), ('30', 1, 1, '', 'left'),
                                         ('M', 3, 1, '', 'left'), ('4.', 1, 2, '', 'center'), ('OUTPUT', 2, 2, '', 'left'), ('40', 1, 1, '', 'left'),
                                         ('HP', 2, 1, '', 'left')],
                                        [('5.', 1, 1, '', 'center'), ('CAPACITY', 3, 1, '', 'left'), ('220', 1, 1, '', 'left'),
                                         ('M3/H', 1, 1, '', ''), ('2 X 100%', 2, 1, '', 'center'), ('30', 1, 1, '', 'left'),
                                         ('KW', 2, 1, '', 'left')],
                                        [('6.', 1, 1, '', 'center'), ('SPEED', 3, 1, '', 'left'), ('1450', 1, 1, '', 'left'),
                                         ('RPM', 3, 1, '', 'left'), ('5.', 1, 1, '', 'center'), ('VOLT', 2, 1, '', 'left'),
                                         ('380 - 415', 2, 1, '', 'left'), ('VOLT', 1, 1, '', '')],
                                        [('7.', 1, 1, '', 'center'), ('DRIVER', 3, 1, '', 'left'), ('30', 1, 1, '', 'left'), ('KW', 3, 1, '', 'left'),
                                         ('6.', 1, 1, '', 'center'), ('CURRENT', 2, 1, '', 'left'), ('53.8', 1, 1, '', 'left'),
                                         ('AMPERE', 2, 1, '', 'left')],
                                        [('8.', 1, 2, '', 'center'), ('BEARING NO.', 3, 2, '', 'left'), ('FRONT', 1, 1, '', 'left'),
                                         ('6311 DDU C3', 2, 1, '', 'center'), ('1 PCS', 1, 1, '', 'left'), ('7.', 1, 2, '', 'center'),
                                         ('BEARING NO.', 2, 2, '', 'left'), ('FRONT', 1, 1, '', ''), ('6312 ZZ', 2, 1, '', 'center')],
                                        [('REAR', 1, 1, '', 'left'), ('6311 DDU C3', 2, 1, '', 'center'), ('1 PCS', 1, 1, '', 'left'),
                                         ('REAR', 1, 1, '', ''), ('6312 ZZ', 2, 1, '', 'center')],
                                        [('9.', 1, 1, '', 'center'), ('DELIVERY TIME', 3, 1, '', 'left'), ('NOV 2010', 4, 1, '', 'left'),
                                         ('8.', 1, 1, '', 'center'), ('SPEED', 2, 1, '', 'left'), ('1470', 1, 1, '', 'left'),
                                         ('RPM', 2, 1, '', 'left')],
                                        [('PUMP DESIGN', 8, 2, 'b', 'center'), ('9.', 1, 1, '', 'center'), ('SER. NO', 2, 1, '', 'left'),
                                         ('H7107137 053', 3, 1, '', 'left')],
                                        [('10.', 1, 2, '', 'center'), ('FAN BLADE', 2, 2, '', 'left'), ('TYPE', 3, 1, '', '')],
                                        [('KKS NO.', 3, 1, '', 'left'), (None, 5, 1, '', ''), ('NO.', 3, 1, '', '')],
                                        [('NO.', 3, 1, '', 'left'), ('2 UNIT ( 2 X 100% )', 5, 1, '', 'left'), ('11.', 1, 1, '', 'center'),
                                         ('WEIGHT', 2, 1, '', 'left'), ('278', 1, 1, '', 'left'), ('KG', 2, 1, '', 'left')],
                                        [('SUCTION PRESSURE', 3, 1, '', 'left'), (None, 2, 1, '', ''), ('KG/CM2 G', 3, 1, '', 'center'),
                                         ('12.', 1, 1, '', 'center'), ('FRAME SIZE', 2, 1, '', 'left'), ('200 LC', 3, 1, '', 'left')],
                                        [('DISCHARGE PRESSURE', 3, 1, '', 'left'), (None, 2, 1, '', ''), ('KG/CM2 G', 3, 1, '', 'center'),
                                         ('SYSTEM', 2, 1, '', 'center'), (None, 4, 1, '', '')],
                                        [('DIFFERENTIAL PRESS.', 3, 1, '', 'left'), (None, 2, 1, '', ''), ('KG/CM2 G', 3, 1, '', 'center'),
                                         ('DRAWING NO.', 2, 1, '', 'center'), (None, 4, 1, '', '')]],
                                       [5.07, 6.6, 8.71, 2.87, 6.41, 8.9, 4.78, 5.65, 4.11, 15.12, 2.87, 6.41, 3.82, 18.66]),
                                      ('images', ['s12_1.jpg', 's12_2.jpg', 's12_3.jpg']),
                                      ('table', [[('MECHANICAL SEAL', 14, 1, 'b', 'center')]],
                                       [5.07, 6.6, 8.71, 2.87, 6.41, 8.9, 4.78, 5.65, 4.11, 15.12, 2.87, 6.41, 3.82, 18.66])]},
 '13. VACUUM PUMP BOP': {'name': 'VACUUM PUMP',
                         'info': {},
                         'col_pct': [4.57, 6.13, 9.92, 2.92, 8.27, 9.05, 4.86, 5.74, 4.18, 12.06, 2.92, 6.52, 3.89, 18.97],
                         'segments': [('table',
                                       [[('SPECIFICATION', 14, 1, 'b', 'center')],
                                        [('NO.', 1, 1, 'b', ''), ('PUMP', 7, 1, 'b', 'center'), ('NO.', 1, 1, 'b', ''),
                                         ('MOTOR', 5, 1, 'b', 'center')],
                                        [('1.', 1, 1, '', 'center'), ('MEREK', 3, 1, '', 'left'), ('KENFLO', 4, 1, '', 'left'),
                                         ('1.', 1, 1, '', 'center'), ('MEREK', 2, 1, '', 'left'),
                                         ('TECO. ELEC. & MACH. PTE. LTD', 3, 1, '', 'left')],
                                        [('2.', 1, 1, '', 'center'), ('TYPE & SIZE', 3, 1, '', 'left'), ('2BF1 101 - 0HD2', 4, 1, '', 'left'),
                                         ('2.', 1, 1, '', 'center'), ('TECO', 2, 1, '', 'left'), ('AEEBKBO47R50FMB', 3, 1, '', 'left')],
                                        [('3.', 1, 1, '', 'center'), ('PRODUCT NO.', 3, 1, '', 'left'), ('1074', 4, 1, '', 'left'),
                                         ('3.', 1, 1, '', 'center'), ('4 POLE', 2, 1, '', 'left'), ('50', 1, 1, '', 'left'), ('HZ', 2, 1, '', '')],
                                        [('4.', 1, 1, '', 'center'), ('TOTAL HEAD', 3, 1, '', 'left'), ('30', 1, 1, '', 'left'),
                                         ('M', 3, 1, '', 'left'), ('4.', 1, 2, '', 'center'), ('OUTPUT', 2, 2, '', 'left'), ('7.5', 1, 1, '', 'left'),
                                         ('HP', 2, 1, '', 'left')],
                                        [('5.', 1, 1, '', 'center'), ('CAPACITY', 3, 1, '', 'left'), ('0.7 - 2.8', 1, 1, '', 'left'),
                                         ('M3/H', 1, 1, '', ''), ('1 X 100%', 2, 1, '', 'center'), ('5.5', 1, 1, '', 'left'),
                                         ('KW', 2, 1, '', 'left')],
                                        [('6.', 1, 1, '', 'center'), ('SPEED', 3, 1, '', 'left'), ('1450', 1, 1, '', 'left'),
                                         ('RPM', 3, 1, '', 'left'), ('5.', 1, 1, '', 'center'), ('VOLT', 2, 1, '', 'left'),
                                         ('380 - 415', 2, 1, '', 'left'), ('VOLT', 1, 1, '', '')],
                                        [('7.', 1, 1, '', 'center'), ('DRIVER', 3, 1, '', 'left'), ('5.5', 1, 1, '', 'left'),
                                         ('KW', 3, 1, '', 'left'), ('6.', 1, 1, '', 'center'), ('CURRENT', 2, 1, '', 'left'),
                                         ('11.4', 1, 1, '', 'left'), ('AMPERE', 2, 1, '', 'left')],
                                        [('8.', 1, 2, '', 'center'), ('BEARING NO.', 3, 2, '', 'left'), ('FRONT', 3, 1, '', 'left'),
                                         ('1 PCS', 1, 1, '', 'left'), ('7.', 1, 2, '', 'center'), ('BEARING NO.', 2, 2, '', 'left'),
                                         ('FRONT', 1, 1, '', ''), ('6306 ZZ', 2, 1, '', 'center')],
                                        [('REAR', 3, 1, '', 'left'), ('1 PCS', 1, 1, '', 'left'), ('REAR', 1, 1, '', ''),
                                         ('6308 ZZ', 2, 1, '', 'center')],
                                        [('9.', 1, 1, '', 'center'), ('DELIVERY TIME', 3, 1, '', 'left'), ('DEC 2010', 4, 1, '', 'left'),
                                         ('8.', 1, 1, '', 'center'), ('SPEED', 2, 1, '', 'left'), ('1445', 1, 1, '', 'left'),
                                         ('RPM', 2, 1, '', 'left')],
                                        [('PUMP DESIGN', 8, 2, 'b', 'center'), ('9.', 1, 1, '', 'center'), ('SER. NO', 2, 1, '', 'left'),
                                         ('H4107014 132', 3, 1, '', 'left')],
                                        [('10.', 1, 2, '', 'center'), ('FAN BLADE', 2, 2, '', 'left'), ('TYPE', 3, 1, '', '')],
                                        [('KKS NO.', 3, 1, '', 'left'), (None, 5, 1, '', ''), ('NO.', 3, 1, '', '')],
                                        [('NO.', 3, 1, '', 'left'), ('1 UNIT ( 1 X 100% )', 5, 1, '', 'left'), ('11.', 1, 1, '', 'center'),
                                         ('WEIGHT', 2, 1, '', 'left'), ('64', 1, 1, '', 'left'), ('KG', 2, 1, '', 'left')],
                                        [('SUCTION PRESSURE', 3, 1, '', 'left'), ('33 - 1013', 2, 1, '', 'center'), ('HPA ( A )', 3, 1, '', 'center'),
                                         ('12.', 1, 1, '', 'center'), ('FRAME SIZE', 2, 1, '', 'left'), ('F 132 S', 3, 1, '', 'left')],
                                        [('DISCHARGE PRESSURE', 3, 1, '', 'left'), ('1013', 2, 1, '', 'center'), ('HPA ( A )', 3, 1, '', 'center'),
                                         ('SYSTEM', 2, 1, '', 'center'), (None, 4, 1, '', '')],
                                        [('DIFFERENTIAL PRESS.', 3, 1, '', 'left'), (None, 2, 1, '', ''), ('KG/CM2 G', 3, 1, '', 'center'),
                                         ('DRAWING NO.', 2, 1, '', 'center'), (None, 4, 1, '', '')]],
                                       [4.57, 6.13, 9.92, 2.92, 8.27, 9.05, 4.86, 5.74, 4.18, 12.06, 2.92, 6.52, 3.89, 18.97])]},
 '14. SEA WATER INTAKE PUMP': {'name': 'SEA WATER INTAKE PUMP',
                               'info': {},
                               'col_pct': [4.47, 5.55, 9.04, 2.69, 6.0, 8.33, 4.47, 8.15, 3.85, 16.12, 2.69, 7.61, 3.58, 17.46],
                               'segments': [('table',
                                             [[('SPECIFICATION', 14, 1, 'b', 'center')],
                                              [('NO.', 1, 1, 'b', ''), ('PUMP', 7, 1, 'b', 'center'), ('NO.', 1, 1, 'b', ''),
                                               ('MOTOR', 5, 1, 'b', 'center')],
                                              [('1.', 1, 1, '', 'center'), ('MEREK', 3, 1, '', 'left'), ('TORISHIMA PUMP', 4, 1, '', 'center'),
                                               ('1.', 1, 1, '', 'center'), ('MEREK', 2, 1, '', 'left'), ('MOTOR SWIP', 3, 1, '', 'center')],
                                              [('2.', 1, 1, '', 'center'), ('TYPE & SIZE', 3, 1, '', 'left'),
                                               ('ETA - N 200 X 150 - 400', 4, 1, '', 'center'), ('2.', 1, 1, '', 'center'),
                                               ('TYPE', 2, 1, '', 'left'), ('3 - W21 - 200L - 06', 3, 1, '', 'center')],
                                              [('3.', 1, 1, '', 'center'), ('PRODUCT NO.', 3, 1, '', 'left'), ('TS1110124', 4, 1, '', 'center'),
                                               ('3.', 1, 1, '', 'center'), ('FREQ.', 2, 1, '', 'left'), ('50', 1, 1, '', 'center'),
                                               ('HZ', 2, 1, '', 'center')],
                                              [('4.', 1, 1, '', 'center'), ('TOTAL HEAD', 3, 1, '', 'left'), ('19.52', 1, 1, '', 'center'),
                                               ('M', 3, 1, '', 'center'), ('4.', 1, 2, '', 'center'), ('OUTPUT', 2, 2, '', 'left'),
                                               ('30', 1, 1, '', 'center'), ('HP', 2, 1, '', 'center')],
                                              [('5.', 1, 1, '', 'center'), ('CAPACITY', 3, 1, '', 'left'), ('247.5', 1, 1, '', 'center'),
                                               ('M3/H', 1, 1, '', 'center'), ('2 X 100%', 2, 1, '', 'center'), ('22', 1, 1, '', 'center'),
                                               ('KW', 2, 1, '', 'center')],
                                              [('6.', 1, 1, '', 'center'), ('SPEED', 3, 1, '', 'left'), ('970', 1, 1, '', 'center'),
                                               ('RPM', 3, 1, '', 'center'), ('5.', 1, 1, '', 'center'), ('VOLT', 2, 1, '', 'left'),
                                               ('380', 2, 1, '', 'center'), ('VOLT', 1, 1, '', 'center')],
                                              [('7.', 1, 1, '', 'center'), ('DRIVER', 3, 1, '', 'left'), ('22', 1, 1, '', 'center'),
                                               ('KW', 3, 1, '', 'center'), ('6.', 1, 1, '', 'center'), ('CURRENT', 2, 1, '', 'left'),
                                               ('43.1', 1, 1, '', 'center'), ('AMPERE', 2, 1, '', 'center')],
                                              [('8.', 1, 2, '', 'center'), ('BEARING NO.', 3, 2, '', 'left'), ('FRONT', 1, 1, '', 'center'),
                                               ('6313 DDU C3', 2, 1, '', 'center'), ('1 PCS', 1, 1, '', 'center'), ('7.', 1, 2, '', 'center'),
                                               ('BEARING NO.', 2, 2, '', 'left'), ('FRONT', 3, 1, '', 'center')],
                                              [('REAR', 1, 1, '', 'center'), ('6313 DDU C3', 2, 1, '', 'center'), ('1 PCS', 1, 1, '', 'center'),
                                               ('REAR', 3, 1, '', 'center')],
                                              [('9.', 1, 1, '', 'center'), ('DELIVERY TIME', 3, 1, '', 'left'), ('JUN 2011', 4, 1, '', 'center'),
                                               ('8.', 1, 1, '', 'center'), ('SPEED', 2, 1, '', 'left'), (None, 1, 1, '', ''),
                                               ('RPM', 2, 1, '', 'center')],
                                              [('PUMP DESIGN', 8, 2, 'b', 'center'), ('9.', 1, 1, '', 'center'), ('SER. NO', 2, 1, '', 'left'),
                                               ('10/08 1008670658', 3, 1, '', 'center')],
                                              [('10.', 1, 2, '', 'center'), ('FAN BLADE', 2, 2, '', 'left'), ('TYPE', 3, 1, '', 'center')],
                                              [('KKS NO.', 3, 1, '', 'left'), (None, 5, 1, '', ''), ('NO.', 3, 1, '', 'center')],
                                              [('NO.', 3, 1, '', 'left'), ('2 UNIT ( 2 X 100% )', 5, 1, '', 'left'), ('11.', 1, 1, '', 'center'),
                                               ('AMB. TEMP.', 2, 1, '', 'left'), ('40', 1, 1, '', 'center'), ('°C', 2, 1, '', 'center')],
                                              [('SUCTION PRESSURE', 3, 1, '', 'left'), (None, 2, 1, '', ''), ('KG/CM2 G', 3, 1, '', 'center'),
                                               ('12.', 1, 1, '', 'center'), ('FRAME SIZE', 2, 1, '', 'left'), (None, 3, 1, '', '')],
                                              [('DISCHARGE PRESSURE', 3, 1, '', 'left'), (None, 2, 1, '', ''), ('KG/CM2 G', 3, 1, '', 'center'),
                                               ('SYSTEM', 2, 1, '', 'center'), (None, 4, 1, '', '')],
                                              [('DIFFERENTIAL PRESS.', 3, 1, '', 'left'), (None, 2, 1, '', ''), ('KG/CM2 G', 3, 1, '', 'center'),
                                               ('DRAWING NO.', 2, 1, '', 'center'), (None, 4, 1, '', '')]],
                                             [4.47, 5.55, 9.04, 2.69, 6.0, 8.33, 4.47, 8.15, 3.85, 16.12, 2.69, 7.61, 3.58, 17.46]),
                                            ('images', ['s14_1.jpg'])]},
 'COOLING TOWER': {'name': 'COOLING TOWER',
                   'info': {},
                   'col_pct': [3.4, 6.1, 12.51, 2.37, 5.3, 7.36, 8.79, 3.48, 17.1, 2.37, 5.3, 4.12, 21.78],
                   'segments': [('table',
                                 [[('SPECIFICATION', 13, 1, 'b', 'center')],
                                  [('NO.', 2, 1, 'b', ''), ('MOTOR', 5, 1, 'b', 'center'), ('NO.', 1, 1, 'b', ''),
                                   ('COOLING TOWER', 5, 1, 'b', 'center')],
                                  [('1.', 2, 1, '', 'center'), ('TYPE OF MOTOR', 2, 1, '', 'left'), ('3 - PHASE INDUCTION MOTOR', 3, 1, '', 'left'),
                                   ('1.', 1, 1, '', 'center'), ('TYPE', 1, 1, '', ''),
                                   ('MECHANICAL INDUCED DRAFT, COUNTER FLOW', 4, 1, '', 'center')],
                                  [('2.', 2, 1, '', 'center'), ('FRAME', 2, 1, '', 'left'), ('3155 / M', 3, 1, '', 'left'),
                                   ('2.', 1, 1, '', 'center'), ('TOTAL CIRCULATING WATER', 4, 1, '', ''), ('5500 M3/HOUR', 1, 1, '', 'center')],
                                  [('3.', 2, 1, '', 'center'), ('ENCLOSURE', 2, 1, '', 'left'), ('IP 55 ( TEFC )', 3, 1, '', 'left'),
                                   ('3.', 1, 1, '', 'center'), ('HOT ( INLET ) WATER TEMP.', 4, 1, '', ''), ('39 °C', 1, 1, '', 'center')],
                                  [('4.', 2, 1, '', 'center'), ('VOLTAGE', 2, 1, '', 'left'), ('380', 1, 1, '', 'left'), ('VOLT', 2, 1, '', 'left'),
                                   ('4.', 1, 1, '', 'center'), ('COLD ( OUTLET ) WATER TEMP.', 4, 1, '', ''), ('31 °C', 1, 1, '', 'center')],
                                  [('5.', 2, 1, '', 'center'), ('FREQ.', 2, 1, '', 'left'), ('50', 1, 1, '', 'left'), ('HZ', 2, 1, '', 'left'),
                                   ('5.', 1, 1, '', 'center'), ('WET BULB TEMP. AMBIENT', 4, 1, '', ''), ('28 °C', 1, 1, '', 'center')],
                                  [('6.', 2, 1, '', 'center'), ('SPEED', 2, 1, '', 'left'), ('1485', 1, 1, '', 'left'), ('RPM', 2, 1, '', 'left'),
                                   ('6.', 1, 1, '', 'center'), ('TOTAL FAN POWER KW ( DRIVER OUTPUT )', 4, 1, '', ''),
                                   ('249.9 KW @ 2 CELL RUNNING', 1, 1, '', 'center')],
                                  [('7.', 2, 1, '', 'center'), ('DRIVER', 2, 1, '', 'left'), ('145', 1, 1, '', 'left'), ('KW', 2, 1, '', 'left'),
                                   ('7.', 1, 1, '', 'center'), ('DRIFT LOSS ( AT DESIGN COND. )', 4, 1, '', ''), ('1.13 %', 1, 1, '', 'center')],
                                  [('8.', 2, 1, '', 'center'), ('CURRENT', 2, 1, '', ''), ('271', 1, 1, '', 'left'), ('AMPERE', 2, 1, '', ''),
                                   ('8.', 1, 1, '', 'center'), ('EVAPORATION LOSS', 4, 1, '', ''),
                                   ('0.001% OF CIRCULATING FLOW', 1, 1, '', 'center')],
                                  [('9.', 2, 1, '', 'center'), ('INSULATION CLASS', 2, 1, '', ''), ('F', 2, 1, '', 'center'), (None, 1, 1, '', ''),
                                   ('9.', 1, 1, '', 'center'), ('DESIGN SEISMIC LOAD', 4, 1, '', ''), ('0.10 G', 1, 1, '', 'center')],
                                  [(None, 7, 1, '', ''), ('10.', 1, 1, '', 'center'), ('TOWER SITE', 4, 1, '', ''),
                                   ('GROUND LEVEL', 1, 1, '', 'center')],
                                  [(None, 7, 1, '', ''), ('11.', 1, 1, '', 'center'), ('ELEVATION ABOVE SEA LEVEL', 4, 1, '', ''),
                                   ('1 M', 1, 1, '', 'center')],
                                  [(None, 7, 1, '', ''), ('12.', 1, 1, '', 'center'), ('CIRCULATING WATER / CELL', 4, 1, '', ''),
                                   ('2750 M3/HOUR', 1, 1, '', 'center')],
                                  [(None, 7, 1, '', ''), ('13.', 1, 1, '', 'center'), ('TOWER EXPOSURE', 4, 1, '', ''),
                                   ('OUTDOOR', 1, 1, '', 'center')]],
                                 [3.4, 6.1, 12.51, 2.37, 5.3, 7.36, 8.79, 3.48, 17.1, 2.37, 5.3, 4.12, 21.78]),
                                ('images', ['s15_1.jpg'])]}}


main()
